# Generated by Django 5.1.6 on 2025-11-09 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlugText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('text_en', models.CharField(blank=True)),
                ('text_ja', models.CharField(blank=True)),
                ('text_tc', models.CharField(blank=True)),
                ('text_sc', models.CharField(blank=True)),
                ('text_ko', models.CharField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(blank=True)),
                ('text_ja', models.CharField(blank=True)),
                ('text_tc', models.CharField(blank=True)),
                ('text_sc', models.CharField(blank=True)),
                ('text_ko', models.CharField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlavorText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char1', to='A25RW.slugtext')),
                ('char2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char2', to='A25RW.slugtext')),
                ('char3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char3', to='A25RW.slugtext')),
                ('char4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char4', to='A25RW.slugtext')),
                ('desc1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desc1', to='A25RW.text')),
                ('desc2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desc2', to='A25RW.text')),
                ('desc3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desc3', to='A25RW.text')),
                ('desc4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desc4', to='A25RW.text')),
            ],
        ),
    ]
