# Generated by Django 5.1.6 on 2025-11-09 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField(unique=True)),
                ('index', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A25RW.slugtext')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField(unique=True)),
                ('index', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('val1_1', models.IntegerField()),
                ('val1_2', models.IntegerField()),
                ('val2_1', models.IntegerField()),
                ('val2_2', models.IntegerField()),
                ('syn', models.BooleanField(default=False)),
                ('com', models.BooleanField(default=False)),
                ('res', models.BooleanField(default=False)),
                ('inh', models.BooleanField(default=False)),
                ('boo', models.BooleanField(default=False)),
                ('wep', models.BooleanField(default=False)),
                ('arm', models.BooleanField(default=False)),
                ('acc', models.BooleanField(default=False)),
                ('sta', models.BooleanField(default=False)),
                ('exp', models.BooleanField(default=False)),
                ('gatherable', models.BooleanField(default=True)),
                ('icon', models.CharField()),
                ('combo1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tcombo1', to='A25RW.trait')),
                ('combo2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tcombo2', to='A25RW.trait')),
                ('desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_desc', to='A25RW.text')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A25RW.text')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField(unique=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_character_set', to='A25RW.slugtext')),
                ('left_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_left_color_set', to='A25RW.slugtext')),
                ('right_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_right_color_set', to='A25RW.slugtext')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='A25RW.trait')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
