# Generated by Django 5.1.6 on 2025-11-09 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavortext',
            name='char3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char3', to='A25RW.text'),
        ),
        migrations.AlterField(
            model_name='flavortext',
            name='char4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char4', to='A25RW.text'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A25RW.text'),
        ),
        migrations.AlterField(
            model_name='flavortext',
            name='char1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char1', to='A25RW.text'),
        ),
        migrations.AlterField(
            model_name='flavortext',
            name='char2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char2', to='A25RW.text'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='left_color',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='gift',
            name='right_color',
            field=models.SlugField(),
        ),
        migrations.DeleteModel(
            name='SlugText',
        ),
    ]
