# Generated by Django 5.1.6 on 2025-11-09 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0004_alter_flavortext_char3_alter_flavortext_char4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='left_color',
            new_name='lc',
        ),
        migrations.RenameField(
            model_name='gift',
            old_name='right_color',
            new_name='rc',
        ),
    ]
