# Generated by Django 5.1.6 on 2025-11-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0005_rename_left_color_gift_lc_rename_right_color_gift_rc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='val1_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='val1_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='val2_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='val2_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
