# Generated by Django 5.1.6 on 2025-11-10 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0006_alter_trait_val1_1_alter_trait_val1_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField(unique=True)),
                ('index', models.IntegerField()),
                ('flag', models.BooleanField()),
                ('val0_1', models.IntegerField()),
                ('val1_1', models.IntegerField(blank=True, null=True)),
                ('val1_2', models.IntegerField(blank=True, null=True)),
                ('val2_1', models.IntegerField(blank=True, null=True)),
                ('val2_2', models.IntegerField(blank=True, null=True)),
                ('val3_1', models.IntegerField(blank=True, null=True)),
                ('val3_2', models.IntegerField(blank=True, null=True)),
                ('val4_1', models.IntegerField(blank=True, null=True)),
                ('val4_2', models.IntegerField(blank=True, null=True)),
                ('dlc', models.BooleanField(default=False)),
                ('usable', models.BooleanField()),
                ('desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_desc', to='A25RW.text')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A25RW.text')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
