# Generated by Django 5.1.6 on 2025-11-10 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0007_effect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='effect',
            options={'ordering': ['usable', 'index']},
        ),
    ]
