# Generated by Django 5.1.6 on 2025-11-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0008_alter_effect_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='val0_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
