# Generated by Django 5.1.6 on 2025-11-10 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0009_effect_val0_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField(unique=True)),
                ('index', models.IntegerField()),
                ('c1l', models.SlugField(blank=True, max_length=10)),
                ('c1r', models.SlugField(blank=True, max_length=10)),
                ('c2l', models.SlugField(blank=True, max_length=10)),
                ('c2r', models.SlugField(blank=True, max_length=10)),
                ('c3l', models.SlugField(blank=True, max_length=10)),
                ('c3r', models.SlugField(blank=True, max_length=10)),
                ('c4l', models.SlugField(blank=True, max_length=10)),
                ('c4r', models.SlugField(blank=True, max_length=10)),
                ('c5l', models.SlugField(blank=True, max_length=10)),
                ('c5r', models.SlugField(blank=True, max_length=10)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipebook', to='A25RW.item')),
                ('categories', models.ManyToManyField(to='A25RW.category')),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A25RW.flavortext')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A25RW.text')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
