# Generated by Django 5.1.6 on 2025-11-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0010_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='icon',
            field=models.SlugField(blank=True),
        ),
    ]
