# Generated by Django 5.1.6 on 2025-11-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0011_item_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
