# Generated by Django 5.1.6 on 2025-11-11 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0012_item_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='flavor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='A25RW.flavortext'),
        ),
    ]
