# Generated by Django 5.1.6 on 2025-11-11 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0013_alter_item_flavor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavortext',
            name='char2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='char2', to='A25RW.text'),
        ),
        migrations.AlterField(
            model_name='flavortext',
            name='char3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='char3', to='A25RW.text'),
        ),
        migrations.AlterField(
            model_name='flavortext',
            name='char4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='char4', to='A25RW.text'),
        ),
        migrations.AlterField(
            model_name='flavortext',
            name='desc2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desc2', to='A25RW.text'),
        ),
        migrations.AlterField(
            model_name='flavortext',
            name='desc3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desc3', to='A25RW.text'),
        ),
        migrations.AlterField(
            model_name='flavortext',
            name='desc4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desc4', to='A25RW.text'),
        ),
    ]
