# Generated by Django 5.1.6 on 2025-11-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0014_alter_flavortext_char2_alter_flavortext_char3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dlc',
            field=models.BooleanField(default=False),
        ),
    ]
