# Generated by Django 5.1.6 on 2025-11-11 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0015_item_dlc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='flavor',
        ),
        migrations.AddField(
            model_name='item',
            name='char1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_char1', to='A25RW.text'),
        ),
        migrations.AddField(
            model_name='item',
            name='char2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_char2', to='A25RW.text'),
        ),
        migrations.AddField(
            model_name='item',
            name='char3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_char3', to='A25RW.text'),
        ),
        migrations.AddField(
            model_name='item',
            name='char4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_char4', to='A25RW.text'),
        ),
        migrations.AddField(
            model_name='item',
            name='desc1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_desc1', to='A25RW.text'),
        ),
        migrations.AddField(
            model_name='item',
            name='desc2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_desc2', to='A25RW.text'),
        ),
        migrations.AddField(
            model_name='item',
            name='desc3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_desc3', to='A25RW.text'),
        ),
        migrations.AddField(
            model_name='item',
            name='desc4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_desc4', to='A25RW.text'),
        ),
        migrations.DeleteModel(
            name='FlavorText',
        ),
    ]
