# Generated by Django 5.1.6 on 2025-11-11 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0016_remove_item_flavor_item_char1_item_char2_item_char3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A25RW.effect')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='A25RW.item')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('item', 'order')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='effects',
            field=models.ManyToManyField(through='A25RW.ItemEffect', to='A25RW.effect'),
        ),
    ]
