# Generated by Django 5.1.6 on 2025-11-11 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0017_itemeffect_item_effects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemeffect',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A25RW.item'),
        ),
    ]
