# Generated by Django 5.1.6 on 2025-11-11 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0018_alter_itemeffect_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.SlugField(max_length=20)),
                ('rank', models.PositiveSmallIntegerField()),
                ('floor_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('floor_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A25RW.text')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A25RW.item')),
            ],
            options={
                'ordering': ['area', 'tool', 'rank'],
            },
        ),
    ]
