# Generated by Django 5.1.6 on 2025-11-11 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0019_gatherdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='trait',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='A25RW.trait'),
        ),
    ]
