# Generated by Django 5.1.6 on 2025-11-11 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0020_item_trait'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='A25RW.category')),
                ('ing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_ingredient', to='A25RW.item')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='A25RW.item')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('item', 'order')},
            },
        ),
    ]
