# Generated by Django 5.1.6 on 2025-11-11 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0021_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='combo1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_combo1', to='A25RW.trait'),
        ),
        migrations.AlterField(
            model_name='trait',
            name='combo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_combo2', to='A25RW.trait'),
        ),
    ]
