# Generated by Django 5.1.6 on 2025-11-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0022_alter_trait_combo1_alter_trait_combo2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effect',
            name='val0_1',
        ),
        migrations.RemoveField(
            model_name='effect',
            name='val0_2',
        ),
        migrations.AddField(
            model_name='effect',
            name='val5_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='val5_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
