# Generated by Django 5.1.6 on 2025-11-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0023_remove_effect_val0_1_remove_effect_val0_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='uses',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
