# Generated by Django 5.1.6 on 2025-11-13 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0024_item_quantity_item_uses'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree', models.SmallIntegerField(db_index=True)),
                ('ancient', models.BooleanField(default=False)),
                ('row', models.SmallIntegerField()),
                ('col', models.SmallIntegerField()),
                ('down', models.BooleanField(default=False)),
                ('left', models.BooleanField(default=False)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A25RW.text')),
                ('ing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipeingredient', to='A25RW.item')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='A25RW.item')),
            ],
            options={
                'ordering': ['tree', 'row', 'col'],
                'unique_together': {('tree', 'row', 'col')},
            },
        ),
    ]
