# Generated by Django 5.1.6 on 2025-11-13 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0025_recipenode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipenode',
            name='char',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='A25RW.text'),
        ),
    ]
