# Generated by Django 5.1.6 on 2025-11-13 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0026_alter_recipenode_char'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField(unique=True)),
                ('combo', models.ManyToManyField(to='A25RW.item')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A25RW.text')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
