# Generated by Django 5.1.6 on 2025-11-13 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0027_itemmix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A25RW.text')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('price', models.IntegerField()),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('level_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('level_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A25RW.item')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A25RW.shop')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
