# Generated by Django 5.1.6 on 2025-11-13 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0029_quest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField(unique=True)),
                ('index', models.IntegerField()),
                ('hp', models.SmallIntegerField()),
                ('atk', models.SmallIntegerField()),
                ('dfn', models.SmallIntegerField()),
                ('spd', models.SmallIntegerField()),
                ('physical', models.SmallIntegerField()),
                ('magic', models.SmallIntegerField()),
                ('fire', models.SmallIntegerField()),
                ('ice', models.SmallIntegerField()),
                ('air', models.SmallIntegerField()),
                ('bolt', models.SmallIntegerField()),
                ('blind', models.SmallIntegerField()),
                ('paralysis', models.SmallIntegerField()),
                ('poison', models.SmallIntegerField()),
                ('burn', models.SmallIntegerField()),
                ('taunt', models.SmallIntegerField()),
                ('sleep', models.SmallIntegerField()),
                ('daze', models.SmallIntegerField()),
                ('frostbite', models.SmallIntegerField()),
                ('char1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_char1', to='A25RW.text')),
                ('char2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_char2', to='A25RW.text')),
                ('char3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_char3', to='A25RW.text')),
                ('char4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_char4', to='A25RW.text')),
                ('desc1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_desc1', to='A25RW.text')),
                ('desc2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_desc2', to='A25RW.text')),
                ('desc3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_desc3', to='A25RW.text')),
                ('desc4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_desc4', to='A25RW.text')),
                ('drops', models.ManyToManyField(to='A25RW.item')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A25RW.text')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='A25RW.text')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='EnemyArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_min', models.IntegerField(blank=True, null=True)),
                ('floor_max', models.IntegerField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A25RW.text')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A25RW.enemy')),
            ],
        ),
    ]
