# Generated by Django 5.1.6 on 2025-11-14 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0030_enemy_enemyarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='add',
            field=models.ManyToManyField(related_name='addcat', to='A25RW.category'),
        ),
        migrations.AlterField(
            model_name='recipenode',
            name='ing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='A25RW.item'),
        ),
        migrations.AlterField(
            model_name='recipenode',
            name='recipe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='A25RW.item'),
        ),
    ]
