# Generated by Django 5.1.6 on 2025-11-14 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0031_item_add_alter_recipenode_ing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='recipenode',
            name='tree_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='A25RW.recipetree'),
        ),
    ]
