# Generated by Django 5.1.6 on 2025-11-14 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0032_recipetree_recipenode_tree_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipetree',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='A25RW.text'),
            preserve_default=False,
        ),
    ]
