# Generated by Django 5.1.6 on 2025-11-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0033_recipetree_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='dlc',
            field=models.BooleanField(default=False),
        ),
    ]
