# Generated by Django 5.1.6 on 2025-11-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0034_trait_dlc'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='val6_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='val6_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='val7_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='val7_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
