# Generated by Django 5.1.6 on 2025-11-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0035_effect_val6_1_effect_val6_2_effect_val7_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='dlc',
            field=models.BooleanField(default=False),
        ),
    ]
