# Generated by Django 5.1.6 on 2025-11-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A25RW', '0036_enemy_dlc'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipenode',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
