# Generated by Django 3.0.6 on 2021-06-06 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(default='', max_length=500)),
                ('race', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Monster_ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(default='', max_length=500)),
                ('race', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('index', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('atk', models.IntegerField()),
                ('defen', models.IntegerField()),
                ('spd', models.IntegerField()),
                ('fire', models.IntegerField()),
                ('wind', models.IntegerField()),
                ('water', models.IntegerField()),
                ('earth', models.IntegerField()),
                ('level', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('cole', models.IntegerField()),
                ('note', models.CharField(max_length=200)),
                ('isDLC', models.BooleanField(default=False)),
                ('isDX', models.BooleanField(default=False)),
                ('isStrong', models.BooleanField(default=False)),
                ('mon_en', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monsters_a15.Monster_en')),
                ('mon_ja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monsters_a15.Monster_ja')),
            ],
        ),
    ]
