# Generated by Django 3.0.6 on 2021-06-07 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions_a12', '0002_region_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Monster_ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('index', models.IntegerField()),
                ('race', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('atk', models.IntegerField()),
                ('defen', models.IntegerField()),
                ('spd', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('note', models.CharField(max_length=400)),
                ('isDX', models.BooleanField(default=False)),
                ('locations', models.ManyToManyField(to='regions_a12.Region')),
                ('mon_en', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monsters_a12.Monster_en')),
                ('mon_ja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monsters_a12.Monster_ja')),
            ],
        ),
    ]
