# Generated by Django 3.0.6 on 2021-06-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a12', '0002_auto_20210609_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
