# Generated by Django 3.0.6 on 2021-06-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a12', '0004_auto_20210609_0149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='effectline',
            options={'ordering': ['item', 'itemnum', 'number']},
        ),
        migrations.AddField(
            model_name='equip',
            name='chars',
            field=models.ManyToManyField(to='items_a12.Character'),
        ),
    ]
