# Generated by Django 3.0.6 on 2021-06-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a12', '0006_auto_20210609_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
