# Generated by Django 5.0.5 on 2024-06-19 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_a12', '0007_auto_20210609_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='slugname',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='slugname',
            new_name='slug',
        ),
    ]
