# Generated by Django 3.0.6 on 2021-06-12 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills_br1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='flavor',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='heart',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='impact',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='pierce',
        ),
    ]
