# Generated by Django 3.0.6 on 2021-06-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills_br1', '0002_auto_20210612_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='rng',
            field=models.CharField(max_length=20),
        ),
    ]
