# Generated by Django 5.0.5 on 2024-06-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions_a16', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='slugname',
            new_name='slug',
        ),
    ]
