# Generated by Django 3.0.6 on 2021-06-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions_a15', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
