# Generated by Django 4.2.5 on 2023-10-06 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chara_a25', '0003_alter_skill_options_skill_index_alter_skill_val2'),
        ('misc_a25', '0006_alter_name_text_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.IntegerField()),
                ('desc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc_a25.desc')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a25.filterable')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a25.name')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('page', models.IntegerField()),
                ('book', models.IntegerField()),
                ('quant1', models.IntegerField()),
                ('quant2', models.IntegerField(blank=True, null=True)),
                ('quant3', models.IntegerField(blank=True, null=True)),
                ('char1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_char1', to='chara_a25.character')),
                ('char2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_char2', to='chara_a25.character')),
                ('char3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_char3', to='chara_a25.character')),
                ('color1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_color1', to='misc_a25.filterable')),
                ('color2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_color2', to='misc_a25.filterable')),
                ('color3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_color3', to='misc_a25.filterable')),
                ('ing1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ing1', to='items_a25.item')),
                ('ing2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ing2', to='items_a25.item')),
                ('ing3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ing3', to='items_a25.item')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a25.item')),
                ('unlock1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unlock1', to='misc_a25.desc')),
                ('unlock2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unlock2', to='misc_a25.desc')),
                ('unlock3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unlock3', to='misc_a25.desc')),
            ],
            options={
                'ordering': ['x', 'y'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mat_color', to='misc_a25.filterable')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a25.item')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mat_type', to='misc_a25.filterable')),
                ('traits', models.ManyToManyField(to='misc_a25.trait')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val_good', models.IntegerField(default=0)),
                ('val_bad', models.IntegerField(default=0)),
                ('good_hp', models.IntegerField(default=0)),
                ('good_spd', models.IntegerField(default=0)),
                ('good_patk', models.IntegerField(default=0)),
                ('good_matk', models.IntegerField(default=0)),
                ('good_pdef', models.IntegerField(default=0)),
                ('good_mdef', models.IntegerField(default=0)),
                ('bad_hp', models.IntegerField(default=0)),
                ('bad_spd', models.IntegerField(default=0)),
                ('bad_patk', models.IntegerField(default=0)),
                ('bad_matk', models.IntegerField(default=0)),
                ('bad_pdef', models.IntegerField(default=0)),
                ('bad_mdef', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a25.item')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a25.filterable')),
            ],
        ),
        migrations.CreateModel(
            name='CombatItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val_good', models.IntegerField(default=0)),
                ('val_bad', models.IntegerField(default=0)),
                ('pow_good', models.IntegerField(default=0)),
                ('pow_bad', models.IntegerField(default=0)),
                ('uses', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a25.name')),
                ('elem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combat_elem', to='misc_a25.filterable')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a25.item')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a25.filterable')),
                ('traits', models.ManyToManyField(to='misc_a25.trait')),
            ],
        ),
    ]
