# Generated by Django 4.2.5 on 2023-10-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a25', '0002_alter_item_options_alter_material_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.CharField(default='CHANGEME', max_length=50),
            preserve_default=False,
        ),
    ]
