# Generated by Django 4.2.5 on 2023-10-06 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_a25', '0004_alter_equipment_val_bad_alter_equipment_val_good'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['book', 'x', 'y']},
        ),
        migrations.RemoveField(
            model_name='combatitem',
            name='traits',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='page',
        ),
    ]
