# Generated by Django 4.2.5 on 2023-10-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a25', '0006_item_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='limited',
            field=models.BooleanField(default=False),
        ),
    ]
