# Generated by Django 4.2.5 on 2023-10-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara_a25', '0005_character_timestamp_memoria_timestamp'),
        ('items_a25', '0007_item_limited'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('characters', models.ManyToManyField(to='chara_a25.character')),
                ('items', models.ManyToManyField(to='items_a25.item')),
                ('memoria', models.ManyToManyField(to='chara_a25.memoria')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
