# Generated by Django 4.2.5 on 2023-10-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_a25', '0008_latestupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='timestamp',
        ),
    ]
