# Generated by Django 4.2.5 on 2023-10-17 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a25', '0010_delete_update_remove_trait_timestamp'),
        ('items_a25', '0009_remove_item_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a25.desc')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a25.recipetab'),
        ),
    ]
