# Generated by Django 4.2.5 on 2023-10-17 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a25', '0010_delete_update_remove_trait_timestamp'),
        ('items_a25', '0010_recipetab_recipe_tab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tab',
        ),
        migrations.RemoveField(
            model_name='recipetab',
            name='desc',
        ),
        migrations.AddField(
            model_name='recipetab',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='misc_a25.name'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RecipePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_x', models.IntegerField()),
                ('max_x', models.IntegerField()),
                ('desc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc_a25.desc')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a25.recipetab')),
            ],
            options={
                'ordering': ['min_x'],
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a25.recipepage'),
        ),
    ]
