# Generated by Django 4.2.5 on 2023-10-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a25', '0011_remove_recipe_tab_remove_recipetab_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepage',
            name='book',
            field=models.IntegerField(default=0),
        ),
    ]
