# Generated by Django 4.2.6 on 2023-10-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a25', '0013_remove_item_limited_item_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
