# Generated by Django 5.0.2 on 2024-03-24 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_a25', '0016_equipment_val2_bad_equipment_val2_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='char1',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='char2',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='char3',
        ),
    ]
