# Generated by Django 5.0.3 on 2024-05-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a25', '0017_remove_recipe_char1_remove_recipe_char2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatitem',
            name='val2_bad',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='combatitem',
            name='val2_good',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
