# Generated by Django 5.0.5 on 2024-09-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a25', '0018_combatitem_val2_bad_combatitem_val2_good'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['book', 'order']},
        ),
        migrations.AlterModelOptions(
            name='recipepage',
            options={'ordering': ['book']},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='x',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='y',
        ),
        migrations.RemoveField(
            model_name='recipepage',
            name='max_x',
        ),
        migrations.RemoveField(
            model_name='recipepage',
            name='min_x',
        ),
        migrations.AddField(
            model_name='recipe',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
