# Generated by Django 5.1.6 on 2025-03-06 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara_a25', '0025_alter_skill_break6_alter_skill_pow6'),
        ('items_a25', '0019_alter_recipe_options_alter_recipepage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='chara',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chara_a25.character'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ing1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ing1', to='items_a25.item'),
        ),
    ]
