# Generated by Django 3.2.9 on 2021-12-05 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items_brsl', '0007_auto_20211205_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demon_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Demon_ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Demon_sc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Demon_tc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Demon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('char', models.CharField(max_length=15)),
                ('index', models.IntegerField()),
                ('vit', models.IntegerField()),
                ('atk', models.IntegerField()),
                ('dfn', models.IntegerField()),
                ('slash', models.CharField(max_length=4)),
                ('pierce', models.CharField(max_length=4)),
                ('shock', models.CharField(max_length=4)),
                ('tremor', models.CharField(max_length=4)),
                ('warp', models.CharField(max_length=4)),
                ('Demon_en', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demons_brsl.demon_en')),
                ('Demon_ja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demons_brsl.demon_ja')),
                ('Demon_sc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demons_brsl.demon_sc')),
                ('Demon_tc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demons_brsl.demon_tc')),
                ('drops', models.ManyToManyField(to='items_brsl.Item')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
