# Generated by Django 3.2.9 on 2021-12-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demons_brsl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='isDLC',
            field=models.BooleanField(default=False),
        ),
    ]
