# Generated by Django 3.2.9 on 2021-12-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demons_brsl', '0002_demon_isdlc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demon',
            name='pierce',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='shock',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='slash',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='tremor',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
