# Generated by Django 3.2.9 on 2021-12-05 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demons_brsl', '0003_auto_20211205_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demon',
            old_name='Demon_en',
            new_name='demon_en',
        ),
        migrations.RenameField(
            model_name='demon',
            old_name='Demon_ja',
            new_name='demon_ja',
        ),
        migrations.RenameField(
            model_name='demon',
            old_name='Demon_sc',
            new_name='demon_sc',
        ),
        migrations.RenameField(
            model_name='demon',
            old_name='Demon_tc',
            new_name='demon_tc',
        ),
    ]
