# Generated by Django 3.2.9 on 2021-12-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demons_brsl', '0004_auto_20211205_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demon',
            name='warp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
