# Generated by Django 3.0.6 on 2021-06-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions_a15', '0001_initial'),
        ('monsters_a15', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='locations',
            field=models.ManyToManyField(to='regions_a15.Region'),
        ),
    ]
