# Generated by Django 3.2.9 on 2021-12-03 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items_brsl', '0004_auto_20211201_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Effect_ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Effect_sc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Effect_tc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('itemtype', models.CharField(blank=True, max_length=20)),
                ('char', models.CharField(max_length=15)),
                ('index', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Facility_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=270)),
            ],
        ),
        migrations.CreateModel(
            name='Facility_ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=270)),
            ],
        ),
        migrations.CreateModel(
            name='Facility_sc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=270)),
            ],
        ),
        migrations.CreateModel(
            name='Facility_tc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('desc', models.CharField(blank=True, max_length=270)),
            ],
        ),
        migrations.CreateModel(
            name='FacilitySet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_brsl.effect')),
                ('facilities', models.ManyToManyField(to='facilities_brsl.Facility')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('num', models.IntegerField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_cat', to='items_brsl.category')),
                ('effect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_brsl.effect')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities_brsl.facility')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_item', to='items_brsl.item')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='FacilityEffectLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('num', models.IntegerField()),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_effect', to='items_brsl.effect')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities_brsl.facility')),
            ],
            options={
                'ordering': ['line', 'num'],
            },
        ),
        migrations.CreateModel(
            name='FacilityEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('act0', models.CharField(blank=True, max_length=50, null=True)),
                ('val0', models.IntegerField(blank=True, null=True)),
                ('act1', models.CharField(blank=True, max_length=50, null=True)),
                ('val1', models.IntegerField(blank=True, null=True)),
                ('act2', models.CharField(blank=True, max_length=50, null=True)),
                ('val3', models.IntegerField(blank=True, null=True)),
                ('eff_en', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facilities_brsl.effect_en')),
                ('eff_ja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facilities_brsl.effect_ja')),
                ('eff_sc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facilities_brsl.effect_sc')),
                ('eff_tc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facilities_brsl.effect_tc')),
            ],
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_en',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facilities_brsl.facility_en'),
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_ja',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facilities_brsl.facility_ja'),
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_sc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facilities_brsl.facility_sc'),
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_tc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facilities_brsl.facility_tc'),
        ),
    ]
