# Generated by Django 3.2.9 on 2021-12-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities_brsl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityeffect',
            name='slugname',
        ),
    ]
