# Generated by Django 3.2.9 on 2021-12-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities_brsl', '0003_rename_val3_facilityeffect_val2'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityeffect',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
