# Generated by Django 3.2.9 on 2021-12-04 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities_brsl', '0004_facilityeffect_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='slugname',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='itemtype',
        ),
    ]
