# Generated by Django 3.2.9 on 2021-12-04 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities_brsl', '0005_auto_20211204_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityset',
            name='effect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities_brsl.facilityeffect'),
        ),
    ]
