# Generated by Django 3.2.9 on 2021-12-04 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities_brsl', '0006_alter_facilityset_effect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityeffectline',
            name='effect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_effect', to='facilities_brsl.facilityeffect'),
        ),
    ]
