# Generated by Django 3.2.9 on 2021-12-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities_brsl', '0007_alter_facilityeffectline_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='isDLC',
            field=models.BooleanField(default=False),
        ),
    ]
