# Generated by Django 3.2.9 on 2021-12-11 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities_brsl', '0008_facility_isdlc'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityEffData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_eff', to='facilities_brsl.facilityeffect')),
            ],
            options={
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='FacilityEffLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('effectdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities_brsl.facilityeffdata')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities_brsl.facility')),
            ],
            options={
                'ordering': ['line'],
            },
        ),
    ]
