# Generated by Django 3.2.9 on 2021-12-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities_brsl', '0009_facilityeffdata_facilityeffline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityeffline',
            name='effectdata',
        ),
        migrations.AddField(
            model_name='facilityeffline',
            name='effectdata',
            field=models.ManyToManyField(to='facilities_brsl.FacilityEffData'),
        ),
    ]
