# Generated by Django 3.2.9 on 2021-12-12 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_brsl', '0010_effdata_effline'),
        ('facilities_brsl', '0010_auto_20211211_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_brsl.category')),
                ('effect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_brsl.effect')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_brsl.item')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityIng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('facility', models.ManyToManyField(to='facilities_brsl.IngData')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
    ]
