# Generated by Django 3.2.9 on 2021-12-12 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities_brsl', '0011_facilitying_ingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitying',
            name='data',
            field=models.ManyToManyField(to='facilities_brsl.IngData'),
        ),
        migrations.RemoveField(
            model_name='facilitying',
            name='facility',
        ),
        migrations.AddField(
            model_name='facilitying',
            name='facility',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facilities_brsl.facility'),
            preserve_default=False,
        ),
    ]
