# Generated by Django 4.0.3 on 2022-03-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities_brsl', '0012_auto_20211212_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityingredient',
            name='category',
        ),
        migrations.RemoveField(
            model_name='facilityingredient',
            name='effect',
        ),
        migrations.RemoveField(
            model_name='facilityingredient',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='facilityingredient',
            name='item',
        ),
        migrations.DeleteModel(
            name='FacilityEffectLine',
        ),
        migrations.DeleteModel(
            name='FacilityIngredient',
        ),
    ]
