# Generated by Django 3.0.6 on 2021-06-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a15', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip',
            name='mp',
            field=models.IntegerField(default=0),
        ),
    ]
