# Generated by Django 3.0.6 on 2021-06-06 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_a15', '0002_equip_mp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disassemble',
            name='dis2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disassembly2', to='items_a15.Item'),
        ),
    ]
