# Generated by Django 3.0.6 on 2021-06-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions_a15', '0002_fieldevent'),
        ('monsters_a15', '0002_monster_locations'),
        ('items_a15', '0004_areadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='areadata',
            name='fieldevent',
            field=models.ManyToManyField(to='regions_a15.FieldEvent'),
        ),
        migrations.AlterField(
            model_name='areadata',
            name='items',
            field=models.ManyToManyField(to='items_a15.Item'),
        ),
        migrations.AlterField(
            model_name='areadata',
            name='maxitem',
            field=models.ManyToManyField(related_name='MaxItem', to='items_a15.Item'),
        ),
        migrations.AlterField(
            model_name='areadata',
            name='monsters',
            field=models.ManyToManyField(to='monsters_a15.Monster'),
        ),
        migrations.AlterField(
            model_name='areadata',
            name='rare',
            field=models.ManyToManyField(related_name='RareItem', to='items_a15.Item'),
        ),
    ]
