# Generated by Django 3.0.6 on 2021-06-07 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_a15', '0008_auto_20210607_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disassembly',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a15.Item'),
        ),
    ]
