# Generated by Django 3.0.6 on 2021-06-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters_a15', '0002_monster_locations'),
        ('items_a15', '0012_relic_regiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiondata',
            name='strong',
            field=models.ManyToManyField(to='monsters_a15.Monster'),
        ),
    ]
