# Generated by Django 3.2.9 on 2021-12-01 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('cat_en', models.CharField(max_length=50)),
                ('cat_ja', models.CharField(max_length=50)),
                ('cat_sc', models.CharField(max_length=50)),
                ('cat_tc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('attTag0', models.CharField(blank=True, max_length=50, null=True)),
                ('actTag0', models.CharField(blank=True, max_length=50, null=True)),
                ('min_1_0', models.CharField(blank=True, max_length=50, null=True)),
                ('max_1_0', models.CharField(blank=True, max_length=50, null=True)),
                ('min_2_0', models.CharField(blank=True, max_length=50, null=True)),
                ('max_2_0', models.CharField(blank=True, max_length=50, null=True)),
                ('actTag1', models.CharField(blank=True, max_length=50, null=True)),
                ('min_1_1', models.CharField(blank=True, max_length=50, null=True)),
                ('max_1_1', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Effect_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Effect_ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Effect_sc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Effect_tc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('itemtype', models.CharField(blank=True, max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('char', models.CharField(max_length=15, unique=True)),
                ('index', models.IntegerField()),
                ('isDLC', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(to='items_brsl.Category')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Item_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=270)),
            ],
        ),
        migrations.CreateModel(
            name='Item_ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=270)),
            ],
        ),
        migrations.CreateModel(
            name='Item_sc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=270)),
            ],
        ),
        migrations.CreateModel(
            name='Item_tc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=270)),
            ],
        ),
        migrations.CreateModel(
            name='LineName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('line_en', models.CharField(max_length=50, unique=True)),
                ('line_ja', models.CharField(max_length=50, unique=True)),
                ('line_sc', models.CharField(max_length=50, unique=True)),
                ('line_tc', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsableItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wt', models.IntegerField()),
                ('cc', models.IntegerField()),
                ('cooltime', models.IntegerField()),
                ('effrange', models.CharField(max_length=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_brsl.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_en',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_brsl.item_en'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_ja',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_brsl.item_ja'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_sc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_brsl.item_sc'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_tc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_brsl.item_tc'),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientcat', to='items_brsl.category')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientitem', to='items_brsl.item')),
                ('synthitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_brsl.item')),
            ],
        ),
        migrations.CreateModel(
            name='EffectLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('number', models.IntegerField()),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_brsl.effect')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_brsl.item')),
                ('linename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_brsl.linename')),
            ],
            options={
                'ordering': ['line', 'number'],
            },
        ),
        migrations.AddField(
            model_name='effect',
            name='eff_en',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_brsl.effect_en'),
        ),
        migrations.AddField(
            model_name='effect',
            name='eff_ja',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_brsl.effect_ja'),
        ),
        migrations.AddField(
            model_name='effect',
            name='eff_sc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_brsl.effect_sc'),
        ),
        migrations.AddField(
            model_name='effect',
            name='eff_tc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_brsl.effect_tc'),
        ),
    ]
