# Generated by Django 3.2.9 on 2021-12-01 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_brsl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='effect_en',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='effect_ja',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='effect_sc',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='effect_tc',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='item_en',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='item_ja',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='item_sc',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='item_tc',
            old_name='description',
            new_name='desc',
        ),
    ]
