# Generated by Django 3.2.9 on 2021-12-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_brsl', '0003_alter_item_char'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='effectline',
            options={'ordering': ['linename', 'number']},
        ),
        migrations.RemoveField(
            model_name='effectline',
            name='line',
        ),
    ]
