# Generated by Django 3.2.9 on 2021-12-04 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_brsl', '0004_auto_20211201_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Unit_ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Unit_sc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Unit_tc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('char1', models.CharField(max_length=15)),
                ('char2', models.CharField(max_length=15)),
                ('char3', models.CharField(max_length=15)),
                ('char4', models.CharField(max_length=15)),
                ('index', models.IntegerField()),
                ('unit_en', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_brsl.effect_en')),
                ('unit_ja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_brsl.effect_ja')),
                ('unit_sc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_brsl.effect_sc')),
                ('unit_tc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_brsl.effect_tc')),
            ],
        ),
    ]
