# Generated by Django 3.2.9 on 2021-12-04 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_brsl', '0005_unit_unit_en_unit_ja_unit_sc_unit_tc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_en',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_brsl.unit_en'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_ja',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_brsl.unit_ja'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_sc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_brsl.unit_sc'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_tc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_brsl.unit_tc'),
        ),
    ]
