# Generated by Django 3.2.9 on 2021-12-05 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_brsl', '0006_auto_20211204_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='slugname',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='linename',
            old_name='slugname',
            new_name='slug',
        ),
    ]
