# Generated by Django 3.2.9 on 2021-12-06 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_brsl', '0008_skillline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slugname',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='effect',
            old_name='slugname',
            new_name='slug',
        ),
    ]
