# Generated by Django 3.2.9 on 2021-12-09 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_brsl', '0009_auto_20211206_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='EffData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_brsl.effect')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='EffLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectdata', models.ManyToManyField(to='items_brsl.EffData')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_brsl.item')),
                ('linename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_brsl.linename')),
            ],
            options={
                'ordering': ['linename'],
            },
        ),
    ]
