# Generated by Django 4.0.3 on 2022-03-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_brsl', '0010_effdata_effline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EffectLine',
        ),
    ]
