# Generated by Django 5.0.5 on 2024-06-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits_a22', '0002_alter_trait_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trait',
            old_name='slugname',
            new_name='slug',
        ),
    ]
