# Generated by Django 3.0.6 on 2021-06-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas_br1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('race', models.CharField(max_length=20)),
                ('hp', models.IntegerField()),
                ('atk', models.IntegerField()),
                ('dfn', models.IntegerField()),
                ('agi', models.IntegerField()),
                ('luk', models.IntegerField()),
                ('impact', models.CharField(max_length=15)),
                ('pierce', models.CharField(max_length=15)),
                ('heart', models.CharField(max_length=15)),
                ('flavor', models.CharField(max_length=500)),
                ('locations', models.ManyToManyField(to='areas_br1.Area')),
            ],
        ),
    ]
