# Generated by Django 3.0.6 on 2021-06-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demons_br1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='index',
            field=models.IntegerField(default=-1),
        ),
    ]
