# Generated by Django 3.2.5 on 2021-07-11 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demons_br1', '0003_auto_20210612_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demon',
            options={'ordering': ['index']},
        ),
    ]
