# Generated by Django 3.2.9 on 2021-12-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills_brsl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['character', 'index']},
        ),
        migrations.AddField(
            model_name='skill',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='range',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
    ]
