# Generated by Django 3.2.9 on 2021-12-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills_brsl', '0002_auto_20211204_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='cycle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='ether',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='ether_rec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='knockback',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
