# Generated by Django 3.2.9 on 2021-12-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills_brsl', '0003_auto_20211204_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='slugname',
            new_name='slug',
        ),
    ]
