# Generated by Django 3.2.9 on 2021-12-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills_brsl', '0004_rename_slugname_skill_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='slug',
        ),
    ]
