# Generated by Django 3.0.6 on 2021-04-13 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items_a22', '0002_auto_20210413_0546'),
        ('locations_a22', '0003_location_isdlc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=270)),
            ],
        ),
        migrations.CreateModel(
            name='Monster_fr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=270)),
            ],
        ),
        migrations.CreateModel(
            name='Monster_ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=270)),
            ],
        ),
        migrations.CreateModel(
            name='Monster_ko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=270)),
            ],
        ),
        migrations.CreateModel(
            name='Monster_sc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=270)),
            ],
        ),
        migrations.CreateModel(
            name='Monster_tc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=270)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('montype', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('index', models.IntegerField()),
                ('isDLC', models.BooleanField(default=False)),
                ('size', models.CharField(max_length=10)),
                ('resist_mag', models.CharField(max_length=10)),
                ('resist_fire', models.CharField(max_length=10)),
                ('resist_ice', models.CharField(max_length=10)),
                ('resist_light', models.CharField(max_length=10)),
                ('resist_wind', models.CharField(max_length=10)),
                ('resist_phys', models.CharField(max_length=10)),
                ('hp_rank', models.IntegerField()),
                ('str_rank', models.IntegerField()),
                ('def_rank', models.IntegerField()),
                ('spd_rank', models.IntegerField()),
                ('ailment1', models.IntegerField()),
                ('ailment2', models.IntegerField()),
                ('ailment3', models.IntegerField()),
                ('ailment4', models.IntegerField()),
                ('ailment5', models.IntegerField()),
                ('ailment6', models.IntegerField()),
                ('ailment7', models.IntegerField()),
                ('ailment8', models.IntegerField()),
                ('ailment9', models.IntegerField()),
                ('ailment10', models.IntegerField()),
                ('drops', models.ManyToManyField(blank=True, to='items_a22.Item')),
                ('location', models.ManyToManyField(to='locations_a22.Location')),
                ('mon_en', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monsters_a22.Monster_en')),
                ('mon_fr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monsters_a22.Monster_fr')),
                ('mon_ja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monsters_a22.Monster_ja')),
                ('mon_ko', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monsters_a22.Monster_ko')),
                ('mon_sc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monsters_a22.Monster_sc')),
                ('mon_tc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monsters_a22.Monster_tc')),
            ],
        ),
    ]
