export const category_to_icon: Record<string, string> = {
    1:  'material-4',
    2:  'material-5',
    3:  'category-uni',
    4:  'category-flowers',
    5:  'category-medicinal',
    6:  'category-poisons',
    7:  'category-elixirs',
    8:  'material-8',
    9:  'material-2',
    10: 'category-ore',
    11: 'material-16',
    12: 'material-6',
    13: 'material-7',
    14: 'material-10',
    15: 'category-fruit',
    16: 'category-beehives',
    17: 'category-mushrooms',
    18: 'category-marine',
    19: 'category-bugs',
    20: 'category-threads',
    21: 'material-1',
    22: 'category-gases',
    23: 'category-puni',
    24: 'category-animal-mat',
    25: 'category-magical',
    26: 'category-neutralizers',
    27: 'material-15',
    28: 'category-jewels',
    29: 'material-11', // ?
    30: 'category-bombs',
    31: 'category-magic-tools',
    32: 'material-3',
    33: 'material-12',
    34: 'category-weapons',
    35: 'category-armor',
    36: 'category-accessories',
    37: 'category-exploration-equip',
    38: 'category-interior',
    39: 'category-enhancement-parts',
    40: 'category-key-items',
    41: 'category-relic',
    42: 'category-materials',
}

export const element_map: Record<string, string> = {
  'air': '#75ff76',
  'fire': '#fcbc72',
  'ice': '#7dfffa',
  'bolt': '#ffff7b',
  'none': '#969696'
}
