# Generated by Django 3.0.6 on 2021-06-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effects_a15', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect_en',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='effect_ja',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
