# Generated by Django 3.0.6 on 2021-04-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effects_a22', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect_en',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='effect_fr',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='effect_ja',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='effect_ko',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='effect_sc',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='effect_tc',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
