# Generated by Django 3.0.6 on 2021-04-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effects_a22', '0002_auto_20210412_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect_en',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='effect_fr',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='effect_ja',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='effect_ko',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='effect_sc',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='effect_tc',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
