# Generated by Django 3.2.9 on 2022-01-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effects_a22', '0005_alter_effect_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='efftype',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Weapon Forge', 'Weapon Forge'), ('Armor Forge', 'Armor Forge'), ('Accessory Forge', 'Accessory Forge'), ('EV', 'EV')], db_index=True, max_length=20),
        ),
    ]
