# Generated by Django 4.0.3 on 2022-03-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effects_a22', '0006_alter_effect_efftype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='effects',
            field=models.ManyToManyField(blank=True, to='effects_a22.effect'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='parent',
            field=models.ManyToManyField(blank=True, to='effects_a22.effect'),
        ),
    ]
