# Generated by Django 5.0.5 on 2024-06-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('effects_a22', '0007_alter_effect_effects_alter_effect_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='effect',
            old_name='slugname',
            new_name='slug',
        ),
    ]
