# Generated by Django 5.0.5 on 2024-06-19 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('effects_a22', '0008_rename_slugname_effect_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='effect_en',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='effect_fr',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='effect_ja',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='effect_ko',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='effect_sc',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='effect_tc',
            old_name='description',
            new_name='desc',
        ),
    ]
