# Generated by Django 4.2.5 on 2023-10-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_a25', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorebattledifficulties',
            name='combat_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorebattledifficulties',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='training',
            name='exp',
            field=models.IntegerField(default=0),
        ),
    ]
