# Generated by Django 4.2.5 on 2023-10-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_a25', '0002_scorebattledifficulties_combat_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorebattle',
            name='difficulties',
        ),
        migrations.AddField(
            model_name='scorebattle',
            name='difficulties',
            field=models.ManyToManyField(to='quest_a25.scorebattledifficulties'),
        ),
    ]
