# Generated by Django 4.2.5 on 2023-10-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_a25', '0004_remove_scorebattledifficulties_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dungeonfloor',
            options={'ordering': ['order']},
        ),
    ]
