# Generated by Django 4.2.5 on 2023-10-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a25', '0010_delete_update_remove_trait_timestamp'),
        ('quest_a25', '0005_alter_dungeonfloor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dungeonfloor',
            name='effects',
            field=models.ManyToManyField(to='misc_a25.desc'),
        ),
        migrations.AlterField(
            model_name='tower',
            name='effects',
            field=models.ManyToManyField(to='misc_a25.desc'),
        ),
        migrations.DeleteModel(
            name='FieldEffect',
        ),
    ]
