# Generated by Django 4.2.7 on 2024-02-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_a25', '0006_alter_dungeonfloor_effects_alter_tower_effects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeon',
            name='gbl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scorebattle',
            name='gbl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='training',
            name='gbl',
            field=models.BooleanField(default=True),
        ),
    ]
