# Generated by Django 5.0.2 on 2024-02-24 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a25', '0017_trait_gbl'),
        ('quest_a25', '0007_dungeon_gbl_scorebattle_gbl_training_gbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeonfloor',
            name='q_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorebattledifficulties',
            name='q_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tower',
            name='gbl',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tower',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc_a25.filterable'),
        ),
        migrations.AddField(
            model_name='tower',
            name='q_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='training',
            name='q_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tower',
            name='floor',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='EnemySkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wt', models.IntegerField(default=0)),
                ('s_id', models.IntegerField(default=0)),
                ('pow1', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemy_area', to='misc_a25.name')),
                ('desc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc_a25.desc')),
                ('elem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a25.filterable')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc_a25.name')),
            ],
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.IntegerField()),
                ('res_ice', models.IntegerField(default=0)),
                ('res_fir', models.IntegerField(default=0)),
                ('res_str', models.IntegerField(default=0)),
                ('res_blt', models.IntegerField(default=0)),
                ('res_sta', models.IntegerField(default=0)),
                ('res_sla', models.IntegerField(default=0)),
                ('res_air', models.IntegerField(default=0)),
                ('base_enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a25.filterable')),
                ('desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a25.desc')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a25.name')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemy_species', to='misc_a25.name')),
                ('burst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest_a25.enemyskill')),
                ('extra', models.ManyToManyField(related_name='extra_skill', to='quest_a25.enemyskill')),
                ('normal', models.ManyToManyField(related_name='normal_skill', to='quest_a25.enemyskill')),
            ],
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a25.desc')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest_a25.enemy')),
            ],
        ),
        migrations.CreateModel(
            name='Wave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('level', models.IntegerField()),
                ('enemies', models.ManyToManyField(to='quest_a25.enemy')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panels', models.ManyToManyField(to='misc_a25.filterable')),
                ('hints', models.ManyToManyField(to='quest_a25.hint')),
                ('waves', models.ManyToManyField(to='quest_a25.wave')),
            ],
        ),
    ]
