# Generated by Django 5.0.2 on 2024-02-24 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a25', '0017_trait_gbl'),
        ('quest_a25', '0009_tower_battle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemyskill',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemy_skill_area', to='misc_a25.name'),
        ),
    ]
