# Generated by Django 5.0.2 on 2024-02-24 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a25', '0017_trait_gbl'),
        ('quest_a25', '0010_alter_enemyskill_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemyskill',
            name='elem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc_a25.filterable'),
        ),
    ]
