# Generated by Django 5.0.2 on 2024-02-25 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_a25', '0012_alter_enemyskill_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='desc',
        ),
    ]
