# Generated by Django 5.0.2 on 2024-02-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_a25', '0013_remove_enemy_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='wave',
            name='w_id',
            field=models.IntegerField(default=0),
        ),
    ]
