# Generated by Django 5.0.2 on 2024-02-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_a25', '0014_wave_w_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='b_id',
            field=models.IntegerField(default=0),
        ),
    ]
