# Generated by Django 5.0.2 on 2024-02-25 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_a25', '0015_battle_b_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorebattledifficulties',
            name='battle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quest_a25.battle'),
        ),
    ]
