# Generated by Django 5.0.2 on 2024-02-25 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_a25', '0016_scorebattledifficulties_battle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tower',
            options={'ordering': ['kind', 'floor']},
        ),
    ]
