# Generated by Django 5.0.2 on 2024-02-25 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_a25', '0017_alter_tower_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest_a25.enemyskill')),
            ],
        ),
        migrations.AddField(
            model_name='enemy',
            name='skills',
            field=models.ManyToManyField(to='quest_a25.skillkind'),
        ),
    ]
