# Generated by Django 5.0.2 on 2024-02-25 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_a25', '0018_skillkind_enemy_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='burst',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='normal',
        ),
    ]
