# Generated by Django 5.0.5 on 2024-05-19 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_a25', '0019_remove_enemy_burst_remove_enemy_extra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dungeonfloor',
            name='rewards',
        ),
    ]
