# Generated by Django 5.0.7 on 2024-10-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_a25', '0020_remove_dungeonfloor_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorebattle',
            name='chap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorebattle',
            name='sect',
            field=models.IntegerField(default=0),
        ),
    ]
