# Generated by Django 5.0.7 on 2024-10-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a25', '0023_alter_name_text_en'),
        ('quest_a25', '0021_scorebattle_chap_scorebattle_sect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorebattle',
            options={'ordering': ['chap', 'sect']},
        ),
        migrations.RemoveConstraint(
            model_name='scorebattle',
            name='score_section',
        ),
        migrations.RemoveField(
            model_name='scorebattle',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='scorebattle',
            name='section',
        ),
        migrations.AddConstraint(
            model_name='scorebattle',
            constraint=models.UniqueConstraint(fields=('chap', 'sect'), name='score_section'),
        ),
    ]
