# Generated by Django 5.0.5 on 2024-06-19 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsters_a22', '0003_rename_slugname_monster_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monster_en',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='monster_fr',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='monster_ja',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='monster_ko',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='monster_sc',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='monster_tc',
            old_name='description',
            new_name='desc',
        ),
    ]
