# Generated by Django 3.0.6 on 2021-06-10 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions_a16', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(default='', max_length=500)),
                ('race', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Monster_ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(default='', max_length=500)),
                ('race', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('kind', models.CharField(max_length=16)),
                ('index', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('atk', models.IntegerField()),
                ('defen', models.IntegerField()),
                ('spd', models.IntegerField()),
                ('level', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('cole', models.IntegerField()),
                ('note', models.CharField(max_length=200)),
                ('locations', models.ManyToManyField(to='regions_a16.Region')),
                ('mon_en', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monsters_a16.Monster_en')),
                ('mon_ja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monsters_a16.Monster_ja')),
            ],
        ),
    ]
