# Generated by Django 3.0.6 on 2021-06-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('points', models.IntegerField()),
                ('reward', models.CharField(max_length=500)),
                ('kind', models.CharField(max_length=30)),
                ('details', models.TextField()),
                ('chapter', models.FloatField()),
                ('number', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
