# Generated by Django 3.0.6 on 2021-06-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions_br1', '0002_mission_slugname'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='character',
            field=models.CharField(default='', max_length=20),
        ),
    ]
