# Generated by Django 3.2.9 on 2021-11-23 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=10)),
                ('char_en', models.CharField(max_length=10)),
                ('char_ja', models.CharField(max_length=10)),
                ('char_sc', models.CharField(max_length=10)),
                ('char_tc', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_en', models.CharField(max_length=200)),
                ('choice_ja', models.CharField(max_length=200)),
                ('choice_sc', models.CharField(max_length=200)),
                ('choice_tc', models.CharField(max_length=200)),
                ('index', models.IntegerField()),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Fragment_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('eff', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fragment_ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('eff', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fragment_sc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('eff', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fragment_tc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('eff', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_en', models.CharField(max_length=30)),
                ('loc_ja', models.CharField(max_length=30)),
                ('loc_sc', models.CharField(max_length=30)),
                ('loc_tc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('size', models.IntegerField()),
                ('gear', models.IntegerField()),
                ('actTag0', models.CharField(max_length=50)),
                ('min1_0', models.CharField(max_length=50)),
                ('max1_0', models.CharField(max_length=50)),
                ('min2_0', models.CharField(max_length=50)),
                ('max2_0', models.CharField(max_length=50)),
                ('actTag1', models.CharField(max_length=50)),
                ('min1_1', models.CharField(max_length=50)),
                ('max1_1', models.CharField(max_length=50)),
                ('frag_en', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fragments_brsl.fragment_en')),
                ('frag_ja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fragments_brsl.fragment_ja')),
                ('frag_sc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fragments_brsl.fragment_sc')),
                ('frag_tc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fragments_brsl.fragment_tc')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('index', models.IntegerField()),
                ('isDLC', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fragments_brsl.character')),
                ('choices', models.ManyToManyField(to='fragments_brsl.Choice')),
                ('fragment', models.ManyToManyField(to='fragments_brsl.Fragment')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fragments_brsl.schoollocations')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
