# Generated by Django 3.2.9 on 2021-11-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragments_brsl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fragment',
            name='frag_en',
        ),
        migrations.RemoveField(
            model_name='fragment',
            name='frag_ja',
        ),
        migrations.RemoveField(
            model_name='fragment',
            name='frag_sc',
        ),
        migrations.RemoveField(
            model_name='fragment',
            name='frag_tc',
        ),
        migrations.AlterField(
            model_name='schoollocations',
            name='loc_en',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='schoollocations',
            name='loc_ja',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='schoollocations',
            name='loc_sc',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='schoollocations',
            name='loc_tc',
            field=models.CharField(max_length=40),
        ),
    ]
