# Generated by Django 3.2.9 on 2021-11-24 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fragments_brsl', '0002_auto_20211124_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragment',
            name='frag_en',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='fragments_brsl.fragment_en'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fragment',
            name='frag_ja',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='fragments_brsl.fragment_ja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fragment',
            name='frag_sc',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='fragments_brsl.fragment_sc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fragment',
            name='frag_tc',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='fragments_brsl.fragment_tc'),
            preserve_default=False,
        ),
    ]
