# Generated by Django 3.2.9 on 2021-12-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragments_brsl', '0004_auto_20211124_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
