# Generated by Django 3.2.9 on 2021-12-07 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fragments_brsl', '0005_character_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['index']},
        ),
    ]
