# Generated by Django 4.1.4 on 2023-03-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a18', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc1', models.CharField(blank=True, max_length=200, null=True)),
                ('desc2', models.CharField(blank=True, max_length=200, null=True)),
                ('desc3', models.CharField(blank=True, max_length=200, null=True)),
                ('desc4', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
