# Generated by Django 4.1.4 on 2023-03-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a18', '0004_remove_basictext_char1_remove_basictext_char2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMastery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_en', models.CharField(max_length=30)),
                ('desc_ja', models.CharField(max_length=30)),
                ('desc_sc', models.CharField(max_length=30)),
                ('desc_tc', models.CharField(max_length=30)),
            ],
        ),
    ]
