# Generated by Django 4.1.7 on 2023-03-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a18', '0005_itemmastery'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=25)),
                ('name_en', models.CharField(max_length=25)),
                ('name_ja', models.CharField(max_length=25)),
                ('name_sc', models.CharField(max_length=25)),
                ('name_tc', models.CharField(max_length=25)),
            ],
        ),
    ]
