# Generated by Django 4.1.7 on 2023-03-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a18', '0006_areaname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaname',
            name='name_en',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='areaname',
            name='slug',
            field=models.SlugField(max_length=35),
        ),
    ]
