# Generated by Django 4.1.7 on 2023-03-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a18', '0007_alter_areaname_name_en_alter_areaname_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='basictext',
            name='desc1_ja',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='basictext',
            name='desc1_sc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='basictext',
            name='desc1_tc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='basictext',
            name='desc2_ja',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='basictext',
            name='desc2_sc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='basictext',
            name='desc2_tc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='basictext',
            name='desc3_ja',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='basictext',
            name='desc3_sc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='basictext',
            name='desc3_tc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='basictext',
            name='desc4_ja',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='basictext',
            name='desc4_sc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='basictext',
            name='desc4_tc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='basictext',
            name='name_ja',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='basictext',
            name='name_sc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='basictext',
            name='name_tc',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
