# Generated by Django 4.1.7 on 2023-03-11 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a18', '0008_basictext_desc1_ja_basictext_desc1_sc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basictext',
            old_name='desc1',
            new_name='desc1_en',
        ),
        migrations.RenameField(
            model_name='basictext',
            old_name='desc2',
            new_name='desc2_en',
        ),
        migrations.RenameField(
            model_name='basictext',
            old_name='desc3',
            new_name='desc3_en',
        ),
        migrations.RenameField(
            model_name='basictext',
            old_name='desc4',
            new_name='desc4_en',
        ),
        migrations.RenameField(
            model_name='basictext',
            old_name='name',
            new_name='name_en',
        ),
    ]
