# Generated by Django 4.1.4 on 2023-02-27 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('effects_traits_a18', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advdata',
            name='baseAtt',
        ),
    ]
