# Generated by Django 4.1.4 on 2023-02-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effects_traits_a18', '0002_remove_advdata_baseatt'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='advanced',
            field=models.ManyToManyField(to='effects_traits_a18.advdata'),
        ),
    ]
