# Generated by Django 3.0.6 on 2021-06-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_a15', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_en',
            name='desc',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
        migrations.AddField(
            model_name='property_ja',
            name='desc',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
    ]
