# Generated by Django 3.2.9 on 2021-12-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties_a15', '0004_auto_20210604_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['index']},
        ),
    ]
