# Generated by Django 5.0.5 on 2024-06-19 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties_a15', '0005_alter_property_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='slugname',
            new_name='slug',
        ),
    ]
