# Generated by Django 3.0.6 on 2021-06-09 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Property_ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('index', models.IntegerField()),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField()),
                ('bomb', models.BooleanField()),
                ('heal', models.BooleanField()),
                ('weapon', models.BooleanField()),
                ('armor', models.BooleanField()),
                ('accessory', models.BooleanField()),
                ('combo1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties_a16.Property')),
                ('combo2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combo_2', to='properties_a16.Property')),
                ('combo3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combo_3', to='properties_a16.Property')),
                ('prop_en', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='properties_a16.Property_en')),
                ('prop_ja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='properties_a16.Property_ja')),
            ],
        ),
    ]
