# Generated by Django 3.2.5 on 2021-07-11 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties_a16', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['index']},
        ),
    ]
