# Generated by Django 3.0.6 on 2021-06-07 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trait_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Trait_ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('index', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('synth', models.BooleanField()),
                ('usable', models.BooleanField()),
                ('ingot', models.BooleanField()),
                ('cloth', models.BooleanField()),
                ('accessory', models.BooleanField()),
                ('note', models.CharField(max_length=400)),
                ('trait_en', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='traits_a12.Trait_en')),
                ('trait_ja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='traits_a12.Trait_ja')),
            ],
        ),
    ]
