# Generated by Django 3.0.6 on 2021-04-11 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location_fr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location_ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location_ko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location_sc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location_tc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('loc_en', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='locations_a22.Location_en')),
                ('loc_fr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='locations_a22.Location_fr')),
                ('loc_ja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='locations_a22.Location_ja')),
                ('loc_ko', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='locations_a22.Location_ko')),
                ('loc_sc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='locations_a22.Location_sc')),
                ('loc_tc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='locations_a22.Location_tc')),
            ],
        ),
    ]
