# Generated by Django 3.0.6 on 2021-04-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations_a22', '0002_location_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='isDLC',
            field=models.BooleanField(default=False),
        ),
    ]
