# Generated by Django 4.1.7 on 2023-03-02 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misc_a18', '0005_itemmastery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=15)),
                ('char1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mchar1', to='misc_a18.character')),
                ('char2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mchar2', to='misc_a18.character')),
                ('char3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mchar3', to='misc_a18.character')),
                ('char4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mchar4', to='misc_a18.character')),
                ('mon_en', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_en', to='misc_a18.basictext')),
                ('mon_ja', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_ja', to='misc_a18.basictext')),
                ('mon_sc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_sc', to='misc_a18.basictext')),
                ('mon_tc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_tc', to='misc_a18.basictext')),
            ],
        ),
    ]
