# Generated by Django 4.1.7 on 2023-03-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters_a18', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='slug',
            field=models.SlugField(),
        ),
    ]
