# Generated by Django 4.1.7 on 2023-03-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters_a18', '0002_alter_monster_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_en', models.CharField(max_length=25)),
                ('race_ja', models.CharField(max_length=25)),
                ('race_sc', models.CharField(max_length=25)),
                ('race_tc', models.CharField(max_length=25)),
                ('icon', models.CharField(max_length=35)),
            ],
        ),
    ]
