# Generated by Django 4.1.7 on 2023-03-05 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a18', '0007_alter_areaname_name_en_alter_areaname_slug'),
        ('monsters_a18', '0003_race'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monster',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='monster',
            name='atk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='cole',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='defen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monsters_a18.race'),
        ),
        migrations.AddField(
            model_name='monster',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='locations',
            field=models.ManyToManyField(to='misc_a18.areaname'),
        ),
        migrations.AddField(
            model_name='monster',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='monster',
            name='spd',
            field=models.IntegerField(default=0),
        ),
    ]
