# Generated by Django 4.1.7 on 2023-03-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters_a18', '0005_monster_ail_monster_fire_monster_ice_monster_impact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='isDX',
            field=models.BooleanField(default=False),
        ),
    ]
