# Generated by Django 3.2.9 on 2021-12-05 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items_brsl', '0007_auto_20211205_0942'),
        ('demons_brsl', '0005_alter_demon_warp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('map', models.CharField(blank=True, max_length=250)),
                ('demons', models.ManyToManyField(to='demons_brsl.Demon')),
                ('items', models.ManyToManyField(to='items_brsl.Item')),
            ],
        ),
        migrations.CreateModel(
            name='AreaName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=50)),
                ('name_ja', models.CharField(max_length=50)),
                ('name_sc', models.CharField(max_length=50)),
                ('name_tc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('areas', models.ManyToManyField(to='regions_brsl.Area')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions_brsl.areaname')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regions_brsl.areaname'),
        ),
    ]
