# Generated by Django 3.2.9 on 2021-12-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions_brsl', '0002_auto_20211205_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='map',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
