# Generated by Django 3.2.9 on 2021-12-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_brsl', '0009_auto_20211206_0019'),
        ('demons_brsl', '0005_alter_demon_warp'),
        ('regions_brsl', '0003_alter_area_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='demons',
            field=models.ManyToManyField(to='demons_brsl.Demon'),
        ),
        migrations.AddField(
            model_name='region',
            name='items',
            field=models.ManyToManyField(to='items_brsl.Item'),
        ),
    ]
