# Generated by Django 4.1.4 on 2023-01-29 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseAtt', models.CharField(blank=True, default='', max_length=50)),
                ('attTag0', models.CharField(blank=True, default='', max_length=50)),
                ('actTag0', models.CharField(blank=True, default='', max_length=50)),
                ('min_1_0', models.CharField(blank=True, default='', max_length=50)),
                ('max_1_0', models.CharField(blank=True, default='', max_length=50)),
                ('min_2_0', models.CharField(blank=True, default='', max_length=50)),
                ('max_2_0', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Text_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Text_ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Text_sc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Text_tc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('index', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('trans_atk', models.BooleanField(default=False)),
                ('trans_heal', models.BooleanField(default=False)),
                ('trans_dbf', models.BooleanField(default=False)),
                ('trans_buff', models.BooleanField(default=False)),
                ('trans_wpn', models.BooleanField(default=False)),
                ('trans_arm', models.BooleanField(default=False)),
                ('trans_acc', models.BooleanField(default=False)),
                ('trans_syn', models.BooleanField(default=False)),
                ('advanced', models.ManyToManyField(to='effects_traits_a21.advdata')),
                ('trait_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effects_traits_a21.text_en')),
                ('trait_ja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effects_traits_a21.text_ja')),
                ('trait_sc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effects_traits_a21.text_sc')),
                ('trait_tc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effects_traits_a21.text_tc')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('index', models.IntegerField()),
                ('advanced', models.ManyToManyField(to='effects_traits_a21.advdata')),
                ('eff_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effects_traits_a21.text_en')),
                ('eff_ja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effects_traits_a21.text_ja')),
                ('eff_sc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effects_traits_a21.text_sc')),
                ('eff_tc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effects_traits_a21.text_tc')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
