# Generated by Django 3.0.6 on 2021-02-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210208_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slugtitle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
