# Generated by Django 3.0.6 on 2021-03-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210208_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='fullname',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
