# Generated by Django 3.0.6 on 2021-03-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_section_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='fullname',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
