# Generated by Django 3.0.6 on 2021-03-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210326_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='slugname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
