# Generated by Django 3.0.6 on 2021-03-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_tags_slugname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='slugname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
