FROM python:3.11.6-alpine3.18
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /backend
COPY requirements.txt /backend
RUN \
 apk add --no-cache python3 postgresql-libs libmemcached-dev zlib-dev && \
 apk add --no-cache --virtual .build-deps gcc python3-dev musl-dev postgresql-dev && \
 python3 -m pip install -r requirements.txt --no-cache-dir && \
 apk --purge del .build-deps
COPY . /backend
CMD python manage.py runserver 0.0.0.0:8000