services:
  postgres:
    image: postgres:16.0
    container_name: postgres
    restart: always
    environment:
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_DB=barrelwisdom'
    volumes:
      - bw_database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    container_name: backend
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.django
    ports:
    - 8000:8000
    environment:
      - 'SECRET_KEY=${SECRET_KEY}'
      - 'DEBUG=${DEBUG}'
      - 'DB_PASSWORD=${DB_PASSWORD}'
      - 'DB_USER=${DB_USER}'
    depends_on:
      - postgres
    volumes:
      - ../backend:/backend

  frontend:
    container_name: frontend
    build: 
      context: ../frontend
      dockerfile: ../docker/Dockerfile.angular
    ports:
      - 4200:4200
    volumes:
      - nodemodules:/frontend/node_modules
      - ../frontend:/frontend
    extra_hosts:
      - "localhost:host-gateway"

  memcached:
    container_name: memcached
    image: memcached:1.6.22-alpine3.18
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64


# For local testing of production build
  frontend_prod:
    container_name: frontend_prod
    image: barrelwisdom/frontend:2-19-24
    ports:
      - 127.0.0.1:4000:4000

  nginx:
    container_name: nginx
    build:
      dockerfile: ./Dockerfile.nginx
    ports:
      - 8080:80

volumes:
  nodemodules: {}
  bw_database: {}