# Generated by Django 3.0.6 on 2021-06-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_a15', '0002_auto_20210604_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_en',
            name='desc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='property_ja',
            name='desc',
            field=models.CharField(default='', max_length=500),
        ),
    ]
