# Generated by Django 3.0.6 on 2021-04-12 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trait_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Trait_fr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Trait_ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Trait_ko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Trait_sc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Trait_tc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('index', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('trans_atk', models.BooleanField(default=False)),
                ('trans_heal', models.BooleanField(default=False)),
                ('trans_dbf', models.BooleanField(default=False)),
                ('trans_buff', models.BooleanField(default=False)),
                ('trans_wpn', models.BooleanField(default=False)),
                ('trans_arm', models.BooleanField(default=False)),
                ('trans_acc', models.BooleanField(default=False)),
                ('trait_en', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='traits_a22.Trait_en')),
                ('trait_fr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='traits_a22.Trait_fr')),
                ('trait_ja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='traits_a22.Trait_ja')),
                ('trait_ko', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='traits_a22.Trait_ko')),
                ('trait_sc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='traits_a22.Trait_sc')),
                ('trait_tc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='traits_a22.Trait_tc')),
            ],
        ),
    ]
