# Generated by Django 3.0.6 on 2021-04-11 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category_fr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category_ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category_ko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category_sc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category_tc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('cat_en', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='categories_a22.Category_en')),
                ('cat_fr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='categories_a22.Category_fr')),
                ('cat_ja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='categories_a22.Category_ja')),
                ('cat_ko', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='categories_a22.Category_ko')),
                ('cat_sc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='categories_a22.Category_sc')),
                ('cat_tc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='categories_a22.Category_tc')),
            ],
        ),
    ]
