# Generated by Django 3.0.6 on 2021-04-11 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_fr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_ko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_sc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_tc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('shop_en', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shops_a22.Shop_en')),
                ('shop_fr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shops_a22.Shop_fr')),
                ('shop_ja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shops_a22.Shop_ja')),
                ('shop_ko', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shops_a22.Shop_ko')),
                ('shop_sc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shops_a22.Shop_sc')),
                ('shop_tc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shops_a22.Shop_tc')),
            ],
        ),
    ]
