# Generated by Django 3.0.6 on 2021-02-08 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slugtitle', models.CharField(default='', max_length=200)),
                ('body', models.TextField()),
                ('image', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(default='', max_length=200)),
                ('authorlock', models.BooleanField(default=False)),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='blog.Section')),
                ('tags', models.ManyToManyField(blank=True, to='blog.Tags')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
