# Generated by Django 3.0.6 on 2021-02-08 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blog',
            unique_together={('slugtitle', 'section')},
        ),
    ]
