# Generated by Django 5.0.5 on 2024-06-19 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='slugtitle',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='slugname',
            new_name='slug',
        ),
        migrations.AlterUniqueTogether(
            name='blog',
            unique_together={('slug', 'section')},
        ),
    ]
