# Generated by Django 5.0.5 on 2024-06-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_slugtitle_blog_slug_rename_slugname_tags_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='desc',
        ),
    ]
