# Generated by Django 5.1.6 on 2025-11-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_description_blog_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='fullname',
            field=models.CharField(blank=True, unique=True),
        ),
    ]
