# Generated by Django 5.1.6 on 2025-11-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_section_name_section_slug_alter_blog_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='fullname',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
