# Generated by Django 5.1.6 on 2025-11-24 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_rename_fullname_section_name_alter_blog_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created']},
        ),
    ]
