# Generated by Django 5.0.5 on 2024-06-19 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fragments_br1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fragment',
            old_name='slugname',
            new_name='slug',
        ),
    ]
