# Generated by Django 3.0.6 on 2021-06-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_br1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='index',
            field=models.IntegerField(default=-1),
        ),
    ]
