# Generated by Django 3.0.6 on 2021-06-09 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category_ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('icon_name', models.SlugField(max_length=150)),
                ('cat_en', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='categories_a16.Category_en')),
                ('cat_ja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='categories_a16.Category_ja')),
            ],
        ),
    ]
