# Generated by Django 3.0.6 on 2021-04-12 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Effect_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Effect_fr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Effect_ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Effect_ko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Effect_sc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Effect_tc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('efftype', models.CharField(choices=[('Normal', 'Normal'), ('Weapon Forge', 'Weapon Forge'), ('Armor Forge', 'Armor Forge'), ('Accessory Forge', 'Accessory Forge'), ('EV', 'EV')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('index', models.IntegerField()),
                ('eff_en', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='effects_a22.Effect_en')),
                ('eff_fr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='effects_a22.Effect_fr')),
                ('eff_ja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='effects_a22.Effect_ja')),
                ('eff_ko', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='effects_a22.Effect_ko')),
                ('eff_sc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='effects_a22.Effect_sc')),
                ('eff_tc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='effects_a22.Effect_tc')),
                ('effects', models.ManyToManyField(blank=True, related_name='_effect_effects_+', to='effects_a22.Effect')),
                ('parent', models.ManyToManyField(blank=True, related_name='_effect_parent_+', to='effects_a22.Effect')),
            ],
        ),
    ]
