# Generated by Django 3.2.5 on 2021-08-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effects_a22', '0003_auto_20210412_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='actTag0',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='actTag1',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='attTag0',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='attTag1',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='effsub',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='effect',
            name='max_1_0',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='max_1_1',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='max_2_0',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='max_2_1',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='min_1_0',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='min_1_1',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='min_2_0',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='min_2_1',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
