# Generated by Django 5.1.6 on 2025-03-27 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items_a26', '0012_necessarymaterial_recipematerial'),
        ('misc_a26', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=70, unique=True)),
                ('break_hits', models.IntegerField()),
                ('break_phys', models.BooleanField()),
                ('fire', models.CharField(blank=True, max_length=10)),
                ('ice', models.CharField(blank=True, max_length=10)),
                ('bolt', models.CharField(blank=True, max_length=10)),
                ('air', models.CharField(blank=True, max_length=10)),
                ('hp', models.IntegerField()),
                ('atk', models.IntegerField()),
                ('dfn', models.IntegerField()),
                ('spd', models.IntegerField()),
                ('desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mdesc', to='misc_a26.text')),
                ('drop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a26.item')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a26.text')),
                ('rare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raredrop', to='items_a26.item')),
                ('trait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a26.trait')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=70, unique=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a26.text')),
            ],
        ),
    ]
