# Generated by Django 5.1.6 on 2025-03-27 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters_a26', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monsters_a26.race'),
            preserve_default=False,
        ),
    ]
