# Generated by Django 5.1.6 on 2025-04-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsters_a26', '0003_monster_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monster',
            options={'ordering': ['id']},
        ),
    ]
