# Generated by Django 5.1.6 on 2025-03-26 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misc_a26', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=70, unique=True)),
                ('wep', models.BooleanField(default=False)),
                ('arm', models.BooleanField(default=False)),
                ('acc', models.BooleanField(default=False)),
                ('atk', models.BooleanField(default=False)),
                ('heal', models.BooleanField(default=False)),
                ('buff', models.BooleanField(default=False)),
                ('dbf', models.BooleanField(default=False)),
                ('fire', models.BooleanField(default=False)),
                ('ice', models.BooleanField(default=False)),
                ('bolt', models.BooleanField(default=False)),
                ('air', models.BooleanField(default=False)),
                ('max_level', models.IntegerField()),
                ('grade_min', models.IntegerField()),
                ('grade_max', models.IntegerField(blank=True, null=True)),
                ('chests', models.ManyToManyField(to='misc_a26.coordinate')),
                ('combo1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tcombo1', to='items_a26.trait')),
                ('combo2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tcombo2', to='items_a26.trait')),
                ('combo3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tcombo3', to='items_a26.trait')),
                ('combo4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tcombo4', to='items_a26.trait')),
                ('desc1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desc1', to='misc_a26.text')),
                ('desc2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desc2', to='misc_a26.text')),
                ('lv_max_rand_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lv_max_rand_range', to='misc_a26.text')),
                ('lv_min_rand_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lv_min_rand_range', to='misc_a26.text')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a26.text')),
                ('trait_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trait_base', to='misc_a26.text')),
                ('trait_hash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trait_hash', to='misc_a26.text')),
            ],
        ),
    ]
