# Generated by Django 5.1.6 on 2025-03-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a26', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trait',
            name='max_level',
        ),
        migrations.AddField(
            model_name='trait',
            name='no_level',
            field=models.BooleanField(default=False),
        ),
    ]
