# Generated by Django 5.1.6 on 2025-03-27 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a26', '0002_remove_trait_max_level_trait_no_level'),
        ('misc_a26', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='desc2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desc2', to='misc_a26.text'),
        ),
    ]
