# Generated by Django 5.1.6 on 2025-03-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a26', '0003_alter_trait_desc2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='lv_max_rand_range',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='lv_min_rand_range',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='trait_base',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='trait_hash',
            field=models.CharField(blank=True, null=True),
        ),
    ]
