# Generated by Django 5.1.6 on 2025-03-27 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a26', '0004_alter_trait_lv_max_rand_range_and_more'),
        ('misc_a26', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='desc1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tdesc1', to='misc_a26.text'),
        ),
        migrations.AlterField(
            model_name='trait',
            name='desc2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tdesc2', to='misc_a26.text'),
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=70, unique=True)),
                ('max_level', models.IntegerField()),
                ('prm1_lv_min_rand_range', models.CharField(blank=True, null=True)),
                ('prm1_lv_max_rand_range', models.CharField(blank=True, null=True)),
                ('prm2_lv_min_rand_range', models.CharField(blank=True, null=True)),
                ('prm2_lv_max_rand_range', models.CharField(blank=True, null=True)),
                ('att_tag', models.CharField(blank=True, null=True)),
                ('act_tag', models.CharField(blank=True, null=True)),
                ('effect_hash', models.CharField(blank=True, null=True)),
                ('desc1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edesc1', to='misc_a26.text')),
                ('desc2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edesc2', to='misc_a26.text')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a26.text')),
            ],
        ),
    ]
