# Generated by Django 5.1.6 on 2025-03-27 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a26', '0005_alter_trait_desc1_alter_trait_desc2_effect'),
        ('misc_a26', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='group',
            field=models.IntegerField(default=-1),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=70, unique=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a26.text')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=70, unique=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a26.text')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=70, unique=True)),
                ('lv', models.IntegerField()),
                ('resonance', models.IntegerField()),
                ('atk', models.IntegerField(blank=True, null=True)),
                ('dfn', models.IntegerField(blank=True, null=True)),
                ('spd', models.IntegerField(blank=True, null=True)),
                ('ct', models.IntegerField(blank=True, null=True)),
                ('aoe', models.BooleanField(blank=True, null=True)),
                ('fire', models.BooleanField(default=False)),
                ('ice', models.BooleanField(default=False)),
                ('bolt', models.BooleanField(default=False)),
                ('air', models.BooleanField(default=False)),
                ('isDLC', models.BooleanField(default=False)),
                ('cats', models.ManyToManyField(to='items_a26.category')),
                ('desc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idesc', to='misc_a26.text')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a26.text')),
                ('mats', models.ManyToManyField(to='items_a26.material')),
            ],
        ),
    ]
