# Generated by Django 5.1.6 on 2025-03-27 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_a26', '0006_trait_group_category_material_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='lv',
        ),
    ]
