# Generated by Django 5.1.6 on 2025-03-27 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a26', '0007_remove_item_lv'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lv', models.IntegerField()),
                ('eff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a26.effect')),
            ],
        ),
        migrations.CreateModel(
            name='ItemStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=70, unique=True)),
                ('rank', models.CharField(max_length=1)),
                ('quality', models.IntegerField()),
                ('eff', models.ManyToManyField(to='items_a26.ingredienteffect')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a26.item')),
            ],
            options={
                'ordering': ['item', 'quality'],
            },
        ),
    ]
