# Generated by Django 5.1.6 on 2025-03-27 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a26', '0008_ingredienteffect_itemstatus'),
        ('misc_a26', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('eff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a26.effect')),
                ('ing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a26.item')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RecipeLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lv', models.IntegerField()),
                ('amt', models.IntegerField(blank=True, null=True)),
                ('fire', models.IntegerField(blank=True, null=True)),
                ('ice', models.IntegerField(blank=True, null=True)),
                ('bolt', models.IntegerField(blank=True, null=True)),
                ('air', models.IntegerField(blank=True, null=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a26.text')),
            ],
            options={
                'ordering': ['lv'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('sp', models.IntegerField()),
                ('kind', models.CharField(max_length=30)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_a26.item')),
                ('recipe', models.ManyToManyField(to='items_a26.recipeeffect')),
                ('level', models.ManyToManyField(to='items_a26.recipelevel')),
            ],
        ),
    ]
