# Generated by Django 5.1.6 on 2025-03-27 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a26', '0009_recipeeffect_recipelevel_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeeffect',
            name='ing',
        ),
        migrations.AddField(
            model_name='recipeeffect',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a26.category'),
        ),
        migrations.AddField(
            model_name='recipeeffect',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a26.item'),
        ),
    ]
