# Generated by Django 5.1.6 on 2025-03-27 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a26', '0010_remove_recipeeffect_ing_recipeeffect_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeeffect',
            name='eff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a26.effect'),
        ),
    ]
