# Generated by Django 5.1.6 on 2025-03-27 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a26', '0011_alter_recipeeffect_eff'),
    ]

    operations = [
        migrations.CreateModel(
            name='NecessaryMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a26.material')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core', models.IntegerField(blank=True, null=True)),
                ('comfort', models.IntegerField(blank=True, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('kind', models.CharField(max_length=50)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_a26.item')),
                ('recipe', models.ManyToManyField(to='items_a26.necessarymaterial')),
            ],
        ),
    ]
