# Generated by Django 5.1.6 on 2025-03-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a26', '0012_necessarymaterial_recipematerial'),
        ('misc_a26', '0002_alter_coordinate_cid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ManyToManyField(to='misc_a26.coordinate'),
        ),
    ]
