# Generated by Django 5.1.6 on 2025-03-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a26', '0013_item_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='comfort_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
