# Generated by Django 5.1.6 on 2025-03-28 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a26', '0014_item_comfort_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraitGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(unique=True)),
            ],
        )
    ]
