# Generated by Django 5.1.6 on 2025-03-28 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_a26', '0015_traitgroup_alter_trait_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trait',
            name='group',
        ),
    ]
