# Generated by Django 5.1.6 on 2025-03-28 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a26', '0016_remove_trait_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a26.traitgroup'),
        ),
    ]
