# Generated by Django 5.1.6 on 2025-03-28 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a26', '0017_trait_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipematerial',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipematerial', to='items_a26.item'),
        ),
    ]
