# Generated by Django 5.1.6 on 2025-03-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a26', '0018_alter_recipematerial_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
