# Generated by Django 5.1.6 on 2025-04-01 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a26', '0019_item_hidden'),
        ('misc_a26', '0004_questdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc_a26.questdata'),
        ),
    ]
