# Generated by Django 5.1.6 on 2025-04-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a26', '0020_item_quest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='effect',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='itemstatus',
            options={'ordering': ['item', '-quality']},
        ),
        migrations.AlterModelOptions(
            name='trait',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='item',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
