# Generated by Django 4.0.6 on 2022-08-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(default='', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('open', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
                ('body', models.TextField(blank=True, null=True)),
                ('comment', models.CharField(default='', max_length=400)),
                ('name', models.CharField(default='Anonymous', max_length=50)),
            ],
            options={
                'ordering': ['modified'],
            },
        ),
    ]
