# Generated by Django 4.1.4 on 2022-12-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='report',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='report',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='report',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='report',
            name='name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='open',
        ),
        migrations.RemoveField(
            model_name='report',
            name='title',
        ),
    ]
