# Generated by Django 3.0.6 on 2021-06-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_a15', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_name',
            field=models.SlugField(default='', max_length=150),
        ),
    ]
