# Generated by Django 3.0.6 on 2021-06-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions_br1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='slugname',
            field=models.SlugField(default='', max_length=300),
        ),
    ]
