# Generated by Django 3.0.6 on 2021-06-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demons_br1', '0002_demon_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='slash',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='heart',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='impact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='pierce',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
