# Generated by Django 5.0.5 on 2024-06-19 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demons_br1', '0004_alter_demon_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demon',
            old_name='slugname',
            new_name='slug',
        ),
    ]
