# Generated by Django 4.1.4 on 2023-03-01 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('effects_traits_a18', '0003_trait_advanced'),
        ('misc_a18', '0002_basictext'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalystAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_en', models.CharField(max_length=80)),
                ('cat_ja', models.CharField(max_length=80)),
                ('cat_sc', models.CharField(max_length=80)),
                ('cat_tc', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=25)),
                ('cat_en', models.CharField(max_length=25)),
                ('cat_ja', models.CharField(max_length=25)),
                ('cat_sc', models.CharField(max_length=25)),
                ('cat_tc', models.CharField(max_length=25)),
                ('icon', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
                ('name_en', models.CharField(max_length=50)),
                ('name_ja', models.CharField(max_length=50)),
                ('name_sc', models.CharField(max_length=50)),
                ('name_tc', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('index', models.IntegerField()),
                ('level', models.IntegerField()),
                ('kind', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('uses', models.IntegerField(blank=True, null=True)),
                ('wt', models.IntegerField(blank=True, null=True)),
                ('stun', models.IntegerField(blank=True, null=True)),
                ('range', models.CharField(blank=True, max_length=15)),
                ('dmin', models.IntegerField(null=True)),
                ('dmax', models.IntegerField(null=True)),
                ('isDLC', models.BooleanField(default=False)),
                ('isDX', models.BooleanField(default=False)),
                ('add', models.ManyToManyField(related_name='add_categories', to='items_a18.category')),
                ('categories', models.ManyToManyField(to='items_a18.category')),
                ('char1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='char1', to='misc_a18.character')),
                ('char2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='char2', to='misc_a18.character')),
                ('char3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='char3', to='misc_a18.character')),
                ('char4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='char4', to='misc_a18.character')),
                ('fixed_components', models.ManyToManyField(to='items_a18.component')),
                ('item_en', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_en', to='misc_a18.basictext')),
                ('item_ja', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_ja', to='misc_a18.basictext')),
                ('item_sc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_sc', to='misc_a18.basictext')),
                ('item_tc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_tc', to='misc_a18.basictext')),
                ('random_components', models.ManyToManyField(related_name='rdm_components', to='items_a18.component')),
                ('traits', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='effects_traits_a18.trait')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField()),
                ('mp', models.IntegerField()),
                ('atk', models.IntegerField()),
                ('dfn', models.IntegerField()),
                ('spd', models.IntegerField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_a18.item')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterEquip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chars', models.ManyToManyField(to='misc_a18.character')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_a18.item')),
            ],
        ),
        migrations.CreateModel(
            name='Catalyst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color1', models.CharField(max_length=10)),
                ('color2', models.CharField(max_length=10)),
                ('color3', models.CharField(max_length=10)),
                ('color4', models.CharField(max_length=10)),
                ('color5', models.CharField(max_length=10)),
                ('color6', models.CharField(max_length=10)),
                ('action1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action1', to='items_a18.catalystaction')),
                ('action2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action2', to='items_a18.catalystaction')),
                ('action3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action3', to='items_a18.catalystaction')),
                ('action4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action4', to='items_a18.catalystaction')),
                ('action5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action5', to='items_a18.catalystaction')),
                ('action6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action6', to='items_a18.catalystaction')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_a18.item')),
            ],
        ),
    ]
