# Generated by Django 4.1.4 on 2023-03-01 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_a18', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='char1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='char2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='char3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='char4',
        ),
    ]
