# Generated by Django 4.1.4 on 2023-03-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a18', '0003_basictext_char1_basictext_char2_basictext_char3_and_more'),
        ('items_a18', '0002_remove_item_char1_remove_item_char2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='chars',
            field=models.ManyToManyField(to='misc_a18.character'),
        ),
        migrations.DeleteModel(
            name='CharacterEquip',
        ),
    ]
