# Generated by Django 4.1.4 on 2023-03-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a18', '0003_item_chars_delete_characterequip'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalyst',
            name='size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
