# Generated by Django 4.1.4 on 2023-03-02 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a18', '0004_remove_basictext_char1_remove_basictext_char2_and_more'),
        ('items_a18', '0007_shopslot_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopslot',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a18.item'),
        ),
        migrations.AlterField(
            model_name='shopslot',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a18.shop'),
        ),
    ]
