# Generated by Django 4.1.4 on 2023-03-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a18', '0011_catalyst_used_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalyst',
            name='used_by',
        ),
        migrations.AddField(
            model_name='item',
            name='catalysts',
            field=models.ManyToManyField(related_name='catalysts', to='items_a18.category'),
        ),
    ]
