# Generated by Django 4.1.7 on 2023-03-02 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_a18', '0012_remove_catalyst_used_by_item_catalysts'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIdea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='recipe_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RecipeUnlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a18.recipeidea')),
            ],
        ),
        migrations.AddField(
            model_name='recipeidea',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a18.item'),
        ),
        migrations.CreateModel(
            name='RecipeCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('condition', models.CharField(max_length=200)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a18.recipeunlock')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
