# Generated by Django 4.1.7 on 2023-03-02 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monsters_a18', '0003_race'),
        ('items_a18', '0013_recipeidea_item_recipe_points_recipeunlock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecondition',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a18.category'),
        ),
        migrations.AddField(
            model_name='recipecondition',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a18.item'),
        ),
        migrations.AddField(
            model_name='recipecondition',
            name='monster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monsters_a18.monster'),
        ),
        migrations.AddField(
            model_name='recipecondition',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monsters_a18.race'),
        ),
    ]
