# Generated by Django 4.1.7 on 2023-03-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a18', '0015_item_locations_item_monsters'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='recipes',
            field=models.ManyToManyField(to='items_a18.item'),
        ),
        migrations.AlterField(
            model_name='book',
            name='recipes',
            field=models.ManyToManyField(related_name='recipe', to='items_a18.item'),
        ),
    ]
