# Generated by Django 4.1.7 on 2023-03-09 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_a18', '0016_item_recipes_alter_book_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a18.item'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='items_a18.item'),
        ),
    ]
