# Generated by Django 4.1.7 on 2023-03-09 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_a18', '0017_item_book_alter_book_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='recipes',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
