# Generated by Django 4.1.7 on 2023-03-09 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_a18', '0018_remove_item_recipes_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='items_a18.item'),
        ),
    ]
