# Generated by Django 4.1.7 on 2023-03-11 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_a18', '0019_alter_item_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_en',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_ja',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_sc',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_tc',
        ),
    ]
