# Generated by Django 4.1.7 on 2023-03-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a18', '0020_rename_item_en_item_text_remove_item_item_ja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecondition',
            name='condition_sc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recipecondition',
            name='condition_tc',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
