# Generated by Django 4.1.7 on 2023-03-13 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_a18', '0021_recipecondition_condition_sc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalyst',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a18.item'),
        ),
    ]
