# Generated by Django 4.1.7 on 2023-03-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_a18', '0022_alter_catalyst_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalyst',
            name='item',
        ),
    ]
