# Generated by Django 4.1.7 on 2023-03-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_a18', '0023_remove_catalyst_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalyst',
            name='action1',
        ),
        migrations.RemoveField(
            model_name='catalyst',
            name='action2',
        ),
        migrations.RemoveField(
            model_name='catalyst',
            name='action3',
        ),
        migrations.RemoveField(
            model_name='catalyst',
            name='action4',
        ),
        migrations.RemoveField(
            model_name='catalyst',
            name='action5',
        ),
        migrations.RemoveField(
            model_name='catalyst',
            name='action6',
        ),
        migrations.RemoveField(
            model_name='catalyst',
            name='color1',
        ),
        migrations.RemoveField(
            model_name='catalyst',
            name='color2',
        ),
        migrations.RemoveField(
            model_name='catalyst',
            name='color3',
        ),
        migrations.RemoveField(
            model_name='catalyst',
            name='color4',
        ),
        migrations.RemoveField(
            model_name='catalyst',
            name='color5',
        ),
        migrations.RemoveField(
            model_name='catalyst',
            name='color6',
        ),
    ]
