# Generated by Django 4.1.7 on 2023-03-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_a18', '0024_remove_catalyst_action1_remove_catalyst_action2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catalyst',
        ),
    ]
