# Generated by Django 4.1.7 on 2023-03-13 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_a18', '0025_delete_catalyst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalyst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('color1', models.CharField(blank=True, max_length=10)),
                ('color2', models.CharField(blank=True, max_length=10)),
                ('color3', models.CharField(blank=True, max_length=10)),
                ('color4', models.CharField(blank=True, max_length=10)),
                ('color5', models.CharField(blank=True, max_length=10)),
                ('color6', models.CharField(blank=True, max_length=10)),
                ('action1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action1', to='items_a18.catalystaction')),
                ('action2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action2', to='items_a18.catalystaction')),
                ('action3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action3', to='items_a18.catalystaction')),
                ('action4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action4', to='items_a18.catalystaction')),
                ('action5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action5', to='items_a18.catalystaction')),
                ('action6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action6', to='items_a18.catalystaction')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_a18.item')),
            ],
        ),
    ]
