# Generated by Django 4.2.5 on 2023-10-05 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(max_length=200)),
                ('text_ja', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filterable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=15, unique=True)),
                ('text_en', models.CharField(max_length=15)),
                ('text_ja', models.CharField(max_length=15)),
                ('kind', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(max_length=40)),
                ('text_ja', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('index', models.IntegerField()),
                ('kind', models.CharField(max_length=10)),
                ('cat', models.CharField(max_length=10)),
                ('val1', models.IntegerField()),
                ('val2', models.IntegerField()),
                ('val3', models.IntegerField()),
                ('val4', models.IntegerField()),
                ('val5', models.IntegerField()),
                ('desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a25.desc')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a25.name')),
                ('trans', models.ManyToManyField(to='misc_a25.filterable')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.IntegerField()),
                ('cole', models.IntegerField()),
                ('level', models.IntegerField()),
                ('desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a25.desc')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kind', to='misc_a25.name')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a25.name')),
                ('req', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='req', to='misc_a25.desc')),
            ],
        ),
    ]
