# Generated by Django 4.2.5 on 2023-10-05 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a25', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a25.filterable'),
        ),
    ]
