# Generated by Django 4.2.5 on 2023-10-05 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a25', '0002_alter_research_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trait_cat', to='misc_a25.filterable'),
        ),
        migrations.AlterField(
            model_name='trait',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trait_kind', to='misc_a25.filterable'),
        ),
        migrations.AlterField(
            model_name='trait',
            name='trans',
            field=models.ManyToManyField(related_name='trait_transfer', to='misc_a25.filterable'),
        ),
    ]
