# Generated by Django 4.2.5 on 2023-10-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a25', '0003_alter_trait_cat_alter_trait_kind_alter_trait_trans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterable',
            name='slug',
            field=models.SlugField(max_length=15),
        ),
    ]
