# Generated by Django 4.2.5 on 2023-10-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a25', '0005_alter_filterable_kind_alter_filterable_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='text_en',
            field=models.CharField(max_length=50),
        ),
    ]
