# Generated by Django 4.2.5 on 2023-10-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a25', '0006_alter_name_text_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='trans_acc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trait',
            name='trans_arm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trait',
            name='trans_atk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trait',
            name='trans_buff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trait',
            name='trans_dbf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trait',
            name='trans_heal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trait',
            name='trans_wep',
            field=models.BooleanField(default=False),
        ),
    ]
