# Generated by Django 4.2.5 on 2023-10-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a25', '0007_trait_trans_acc_trait_trans_arm_trait_trans_atk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
