# Generated by Django 4.2.5 on 2023-10-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a25', '0009_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Update',
        ),
        migrations.RemoveField(
            model_name='trait',
            name='timestamp',
        ),
    ]
