# Generated by Django 4.2.5 on 2023-10-18 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a25', '0010_delete_update_remove_trait_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trait',
            name='trans',
        ),
    ]
