# Generated by Django 4.2.6 on 2023-11-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a25', '0012_trait_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
