# Generated by Django 5.0.2 on 2024-02-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a25', '0015_alter_desc_text_en_alter_name_text_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='desc',
            name='text_sc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='desc',
            name='text_tc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='filterable',
            name='text_sc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='filterable',
            name='text_tc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='name',
            name='text_sc',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='name',
            name='text_tc',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
