# Generated by Django 5.0.2 on 2024-02-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a25', '0016_desc_text_sc_desc_text_tc_filterable_text_sc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='gbl',
            field=models.BooleanField(default=True),
        ),
    ]
