# Generated by Django 5.0.2 on 2024-02-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a25', '0017_trait_gbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desc',
            name='text_en',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
