# Generated by Django 5.0.2 on 2024-02-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a25', '0018_alter_desc_text_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desc',
            name='text_en',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='desc',
            name='text_sc',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='desc',
            name='text_tc',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
