# Generated by Django 5.0.5 on 2024-07-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a25', '0019_alter_desc_text_en_alter_desc_text_sc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='text_en',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
