# Generated by Django 5.0.5 on 2024-08-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a25', '0021_alter_filterable_text_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desc',
            name='text_ja',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
