# Generated by Django 5.0.7 on 2024-10-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a25', '0022_alter_desc_text_ja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='text_en',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
