# Generated by Django 4.0.2 on 2022-03-02 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('effects_a23', '0002_rename_description_effect_en_desc_and_more'),
        ('misc_a23', '0003_alter_character_char_en_alter_character_char_ja_and_more'),
        ('regions_a23', '0001_initial'),
        ('traits_a23', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=25)),
                ('cat_en', models.CharField(max_length=25)),
                ('cat_ja', models.CharField(max_length=25)),
                ('cat_ko', models.CharField(max_length=25)),
                ('cat_sc', models.CharField(max_length=25)),
                ('cat_tc', models.CharField(max_length=25)),
                ('icon', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='EffectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elem', models.IntegerField()),
                ('num', models.IntegerField(blank=True, null=True)),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effects_a23.effect')),
            ],
            options={
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='Item_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc1', models.CharField(blank=True, max_length=200, null=True)),
                ('desc2', models.CharField(blank=True, max_length=200, null=True)),
                ('desc3', models.CharField(blank=True, max_length=200, null=True)),
                ('desc4', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item_ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc1', models.CharField(blank=True, max_length=200, null=True)),
                ('desc2', models.CharField(blank=True, max_length=200, null=True)),
                ('desc3', models.CharField(blank=True, max_length=200, null=True)),
                ('desc4', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item_ko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc1', models.CharField(blank=True, max_length=200, null=True)),
                ('desc2', models.CharField(blank=True, max_length=200, null=True)),
                ('desc3', models.CharField(blank=True, max_length=200, null=True)),
                ('desc4', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item_sc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc1', models.CharField(blank=True, max_length=200, null=True)),
                ('desc2', models.CharField(blank=True, max_length=200, null=True)),
                ('desc3', models.CharField(blank=True, max_length=200, null=True)),
                ('desc4', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item_tc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc1', models.CharField(blank=True, max_length=200, null=True)),
                ('desc2', models.CharField(blank=True, max_length=200, null=True)),
                ('desc3', models.CharField(blank=True, max_length=200, null=True)),
                ('desc4', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('index', models.IntegerField()),
                ('level', models.IntegerField()),
                ('price', models.IntegerField()),
                ('kind', models.CharField(max_length=20)),
                ('categories', models.ManyToManyField(to='items_a23.Category')),
                ('char1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chara1', to='misc_a23.character')),
                ('char2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chara2', to='misc_a23.character')),
                ('char3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chara3', to='misc_a23.character')),
                ('char4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chara4', to='misc_a23.character')),
                ('chest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regions_a23.region')),
                ('item_en', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='it_en', to='items_a23.item_en')),
                ('item_ja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='it_ja', to='items_a23.item_ja')),
                ('item_ko', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='it_ko', to='items_a23.item_ja')),
                ('item_sc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='it_sc', to='items_a23.item_ja')),
                ('item_tc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='it_tc', to='items_a23.item_ja')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc_a23.shop')),
                ('traits', models.ManyToManyField(to='traits_a23.Trait')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField()),
                ('mp', models.IntegerField()),
                ('atk', models.IntegerField()),
                ('dfn', models.IntegerField()),
                ('spd', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a23.item')),
            ],
        ),
        migrations.CreateModel(
            name='EffectLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elem', models.CharField(max_length=10)),
                ('order', models.IntegerField()),
                ('effects', models.ManyToManyField(to='items_a23.EffectData')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a23.item')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CharacterEquip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chars', models.ManyToManyField(to='misc_a23.Character')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a23.item')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('index', models.IntegerField()),
                ('chest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regions_a23.region')),
                ('item_en', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_en', to='items_a23.item_en')),
                ('item_ja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_ja', to='items_a23.item_ja')),
                ('item_ko', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_ko', to='items_a23.item_ja')),
                ('item_sc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_sc', to='items_a23.item_ja')),
                ('item_tc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_tc', to='items_a23.item_ja')),
                ('items', models.ManyToManyField(to='items_a23.Item')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc_a23.shop')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
