# Generated by Django 4.0.2 on 2022-03-02 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_a23', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='slugname',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='slugname',
            new_name='slug',
        ),
    ]
