# Generated by Django 4.0.2 on 2022-03-02 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_a23', '0002_rename_slugname_book_slug_rename_slugname_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effectlines',
            name='elem',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_en',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='it_en', to='items_a23.item_en'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_ja',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='it_ja', to='items_a23.item_ja'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_ko',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='it_ko', to='items_a23.item_ja'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_sc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='it_sc', to='items_a23.item_ja'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_tc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='it_tc', to='items_a23.item_ja'),
        ),
    ]
