# Generated by Django 4.0.2 on 2022-03-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a23', '0004_remove_book_item_en_remove_book_item_ja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_ja',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_ko',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_sc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_tc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
