# Generated by Django 4.0.2 on 2022-03-02 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_a23', '0005_alter_book_book_en_alter_book_book_ja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_en',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a23.item_en'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_ja',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a23.item_ja'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_ko',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a23.item_ko'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_sc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a23.item_sc'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_tc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a23.item_tc'),
        ),
    ]
