# Generated by Django 4.0.3 on 2022-03-02 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_a23', '0006_alter_item_item_en_alter_item_item_ja_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='chest',
        ),
        migrations.RemoveField(
            model_name='item',
            name='chest',
        ),
    ]
