# Generated by Django 4.0.3 on 2022-03-04 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_a23', '0007_remove_book_chest_remove_item_chest'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterequip',
            name='it',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a23.item'),
        ),
        migrations.AddField(
            model_name='equip',
            name='it',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a23.item'),
        ),
        migrations.AlterField(
            model_name='characterequip',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remove_it', to='items_a23.item'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remove_it2', to='items_a23.item'),
        ),
    ]
