# Generated by Django 4.0.3 on 2022-03-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_a23', '0008_characterequip_it_equip_it_alter_characterequip_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterequip',
            name='item',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='item',
        ),
    ]
