# Generated by Django 4.0.3 on 2022-03-04 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_a23', '0009_remove_characterequip_item_remove_equip_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effectlines',
            name='effects',
        ),
        migrations.AddField(
            model_name='book',
            name='note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='effectdata',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a23.effectlines'),
        ),
    ]
