# Generated by Django 4.0.3 on 2022-03-04 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('effects_a23', '0002_rename_description_effect_en_desc_and_more'),
        ('items_a23', '0011_item_char_item_quantity_item_range_item_uses_item_wt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_en', models.CharField(blank=True, max_length=30, null=True)),
                ('com_ja', models.CharField(blank=True, max_length=30, null=True)),
                ('com_ko', models.CharField(blank=True, max_length=30, null=True)),
                ('com_sc', models.CharField(blank=True, max_length=30, null=True)),
                ('com_tc', models.CharField(blank=True, max_length=30, null=True)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a23.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='maxlv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='restrict',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='effectdata',
            name='effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='effects_a23.effect'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a23.item'),
        ),
        migrations.AddField(
            model_name='effectdata',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a23.component'),
        ),
        migrations.AddField(
            model_name='item',
            name='components',
            field=models.ManyToManyField(to='items_a23.component'),
        ),
    ]
