# Generated by Django 4.0.3 on 2022-03-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a23', '0012_component_ingredient_cat_item_maxlv_item_restrict_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ing',
            new_name='synth',
        ),
        migrations.RemoveField(
            model_name='item',
            name='maxlv',
        ),
        migrations.RemoveField(
            model_name='item',
            name='restrict',
        ),
        migrations.AddField(
            model_name='effectlines',
            name='maxlv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='effectlines',
            name='restrict',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
