# Generated by Django 4.0.3 on 2022-03-06 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_a23', '0013_rename_ing_ingredient_synth_remove_item_maxlv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effectdata',
            name='elem',
        ),
    ]
