# Generated by Django 4.0.3 on 2022-03-06 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_a23', '0014_remove_effectdata_elem'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a23.item')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIdea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('hor', models.BooleanField(default=False)),
                ('ver', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a23.item')),
            ],
            options={
                'ordering': ['row', 'col'],
            },
        ),
    ]
