# Generated by Django 4.0.3 on 2022-03-06 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a23', '0003_alter_character_char_en_alter_character_char_ja_and_more'),
        ('items_a23', '0015_recipetext_recipeidea'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeidea',
            name='char',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='misc_a23.character'),
            preserve_default=False,
        ),
    ]
