# Generated by Django 4.0.3 on 2022-03-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a23', '0016_recipeidea_char'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipetext',
            old_name='text',
            new_name='text_en',
        ),
        migrations.AddField(
            model_name='recipetext',
            name='text_ja',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipetext',
            name='text_ko',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipetext',
            name='text_sc',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipetext',
            name='text_tc',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
