# Generated by Django 4.0.3 on 2022-03-06 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_a23', '0017_rename_text_recipetext_text_en_recipetext_text_ja_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeidea',
            options={'ordering': ['char', 'row', 'col']},
        ),
    ]
