# Generated by Django 4.0.3 on 2022-03-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a23', '0018_alter_recipeidea_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='add',
            field=models.ManyToManyField(related_name='add_categories', to='items_a23.category'),
        ),
    ]
