# Generated by Django 4.0.3 on 2022-03-17 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_a23', '0019_item_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isDLC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='from_seed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a23.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='isDLC',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_a23.item')),
            ],
        ),
    ]
