# Generated by Django 4.0.3 on 2022-03-17 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_a23', '0020_book_isdlc_item_from_seed_item_isdlc_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='from_seed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seedset', to='items_a23.item'),
        ),
    ]
