# Generated by Django 4.0.3 on 2022-03-17 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_a23', '0021_alter_item_from_seed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seed',
        ),
    ]
