# Generated by Django 3.0.6 on 2021-06-12 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas_br1', '0001_initial'),
        ('demons_br1', '0001_initial'),
        ('missions_br1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('effect', models.CharField(max_length=200)),
                ('acquisition', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=30)),
                ('demons', models.ManyToManyField(to='demons_br1.Demon')),
                ('locations', models.ManyToManyField(to='areas_br1.Area')),
                ('missions', models.ManyToManyField(to='missions_br1.Mission')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('craftitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_br1.Item')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientitem', to='items_br1.Item')),
            ],
        ),
    ]
