# Generated by Django 3.2.5 on 2021-07-11 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_br1', '0002_item_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['index']},
        ),
    ]
