# Generated by Django 3.0.6 on 2021-06-10 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories_a16', '0001_initial'),
        ('regions_a16', '0001_initial'),
        ('effects_a16', '0001_initial'),
        ('properties_a16', '0001_initial'),
        ('monsters_a16', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Item_ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('index', models.IntegerField()),
                ('level', models.IntegerField()),
                ('slots', models.IntegerField()),
                ('evalue', models.IntegerField()),
                ('fire', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('wind', models.BooleanField(default=False)),
                ('earth', models.BooleanField(default=False)),
                ('effect', models.IntegerField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('kind', models.CharField(max_length=16)),
                ('categories', models.ManyToManyField(to='categories_a16.Category')),
                ('item_en', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_a16.Item_en')),
                ('item_ja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_a16.Item_ja')),
                ('locations', models.ManyToManyField(to='regions_a16.Region')),
                ('monsters', models.ManyToManyField(to='monsters_a16.Monster')),
                ('properties', models.ManyToManyField(to='properties_a16.Property')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientcat', to='categories_a16.Category')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientitem', to='items_a16.Item')),
                ('synthitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a16.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField()),
                ('mp', models.IntegerField(default=0)),
                ('atk', models.IntegerField()),
                ('defen', models.IntegerField()),
                ('spd', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a16.Item')),
            ],
        ),
        migrations.CreateModel(
            name='EffectLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elem', models.CharField(max_length=10)),
                ('hidden', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('number', models.IntegerField()),
                ('min_elem', models.IntegerField()),
                ('max_elem', models.IntegerField()),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effects_a16.Effect')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a16.Item')),
            ],
            options={
                'ordering': ['elem', 'order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Disassembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis', models.ManyToManyField(related_name='disassembleitem', to='items_a16.Item')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a16.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Disassembled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a16.Item')),
                ('parent', models.ManyToManyField(related_name='disassembledparent', to='items_a16.Item')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterEquip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chars', models.ManyToManyField(to='items_a16.Character')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a16.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('note', models.CharField(max_length=200)),
                ('index', models.IntegerField()),
                ('item_en', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_a16.Item_en')),
                ('item_ja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_a16.Item_ja')),
                ('items', models.ManyToManyField(to='items_a16.Item')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
