# Generated by Django 3.0.6 on 2021-06-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a16', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='note',
            field=models.CharField(default='', max_length=200),
        ),
    ]
