# Generated by Django 5.0.5 on 2024-06-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations_a22', '0003_location_isdlc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='slugname',
            new_name='slug',
        ),
    ]
