# Generated by Django 3.0.6 on 2021-06-06 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('effects_a15', '0002_auto_20210605_2210'),
        ('monsters_a15', '0002_monster_locations'),
        ('properties_a15', '0004_auto_20210604_2130'),
        ('categories_a15', '0002_category_icon_name'),
        ('regions_a15', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('index', models.IntegerField()),
                ('level', models.IntegerField()),
                ('evalue', models.IntegerField()),
                ('fire', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('wind', models.BooleanField(default=False)),
                ('earth', models.BooleanField(default=False)),
                ('effect', models.IntegerField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('itype', models.CharField(max_length=15)),
                ('isDLC', models.BooleanField(default=False)),
                ('isDX', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(to='categories_a15.Category')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Item_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Item_ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Relic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ManyToManyField(related_name='areas', to='regions_a15.Region')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a15.Item')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions_a15.Region')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_en',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_a15.Item_en'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_ja',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_a15.Item_ja'),
        ),
        migrations.AddField(
            model_name='item',
            name='locations',
            field=models.ManyToManyField(to='regions_a15.Region'),
        ),
        migrations.AddField(
            model_name='item',
            name='monsters',
            field=models.ManyToManyField(to='monsters_a15.Monster'),
        ),
        migrations.AddField(
            model_name='item',
            name='properties',
            field=models.ManyToManyField(to='properties_a15.Property'),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientcat', to='categories_a15.Category')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientitem', to='items_a15.Item')),
                ('synthitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a15.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField()),
                ('atk', models.IntegerField()),
                ('defen', models.IntegerField()),
                ('spd', models.IntegerField()),
                ('fire', models.IntegerField()),
                ('wind', models.IntegerField()),
                ('water', models.IntegerField()),
                ('earth', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a15.Item')),
            ],
        ),
        migrations.CreateModel(
            name='EffectLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elem', models.CharField(max_length=5)),
                ('number', models.IntegerField()),
                ('min_elem', models.IntegerField()),
                ('max_elem', models.IntegerField()),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effects_a15.Effect')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a15.Item')),
            ],
            options={
                'ordering': ['elem', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Disassemble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disassembly1', to='items_a15.Item')),
                ('dis2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disassembly2', to='items_a15.Item')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a15.Item')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterEquip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chars', models.ManyToManyField(to='items_a15.Character')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a15.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('acquisition', models.CharField(max_length=200)),
                ('index', models.IntegerField()),
                ('item_en', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_a15.Item_en')),
                ('item_ja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_a15.Item_ja')),
                ('items', models.ManyToManyField(to='items_a15.Item')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
