# Generated by Django 3.0.6 on 2021-06-07 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_a15', '0005_auto_20210606_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disassembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis', models.ManyToManyField(related_name='disassembleitem', to='items_a15.Item')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_a15.Item')),
            ],
        ),
    ]
