# Generated by Django 3.0.6 on 2021-06-19 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions_a15', '0002_fieldevent'),
        ('items_a15', '0010_disassembled'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areas', models.ManyToManyField(to='items_a15.AreaData')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions_a15.Region')),
            ],
        ),
    ]
