# Generated by Django 3.0.6 on 2021-06-19 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_a15', '0011_regiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='relic',
            name='regiondata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a15.RegionData'),
        ),
    ]
