# Generated by Django 5.0.5 on 2024-06-19 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_a15', '0013_regiondata_strong'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='slugname',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='slugname',
            new_name='slug',
        ),
    ]
