# Generated by Django 3.0.6 on 2021-06-09 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions_a12', '0002_region_parent'),
        ('monsters_a12', '0001_initial'),
        ('items_a12', '0007_auto_20210609_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlock', models.CharField(max_length=15)),
                ('note', models.CharField(max_length=400)),
                ('ingredients', models.ManyToManyField(to='items_a12.Item')),
                ('monsters', models.ManyToManyField(to='monsters_a12.Monster')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions_a12.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.ManyToManyField(to='areadata_a12.Field')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions_a12.Region')),
            ],
        ),
    ]
