# Generated by Django 3.0.6 on 2021-04-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a22', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_en',
            name='description',
            field=models.CharField(blank=True, max_length=270),
        ),
        migrations.AlterField(
            model_name='item_fr',
            name='description',
            field=models.CharField(blank=True, max_length=270),
        ),
        migrations.AlterField(
            model_name='item_ja',
            name='description',
            field=models.CharField(blank=True, max_length=270),
        ),
        migrations.AlterField(
            model_name='item_ko',
            name='description',
            field=models.CharField(blank=True, max_length=270),
        ),
        migrations.AlterField(
            model_name='item_sc',
            name='description',
            field=models.CharField(blank=True, max_length=270),
        ),
        migrations.AlterField(
            model_name='item_tc',
            name='description',
            field=models.CharField(blank=True, max_length=270),
        ),
    ]
