# Generated by Django 3.0.6 on 2021-04-14 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations_a22', '0003_location_isdlc'),
        ('items_a22', '0003_ingeffects_noneffect'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority1', models.IntegerField(blank=True, null=True)),
                ('priority2', models.IntegerField(blank=True, null=True)),
                ('priority3', models.IntegerField(blank=True, null=True)),
                ('tool', models.CharField(max_length=15)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations_a22.Location')),
                ('rank1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank1', to='items_a22.Item')),
                ('rank2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rank2', to='items_a22.Item')),
                ('rank3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rank3', to='items_a22.Item')),
            ],
        ),
    ]
