# Generated by Django 3.0.6 on 2021-04-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a22', '0004_itemlocations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlocations',
            name='tool',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
