# Generated by Django 3.0.6 on 2021-05-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a22', '0008_itemareas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemareas',
            name='gatherdata',
        ),
        migrations.AddField(
            model_name='itemareas',
            name='gatherdata',
            field=models.ManyToManyField(to='items_a22.ItemLocations'),
        ),
    ]
