# Generated by Django 5.1.6 on 2025-03-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('z', models.IntegerField()),
                ('cid', models.IntegerField()),
                ('label', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(blank=True, max_length=500)),
                ('text_ja', models.CharField(blank=True, max_length=500)),
                ('text_tc', models.CharField(blank=True, max_length=500)),
                ('text_sc', models.CharField(blank=True, max_length=500)),
                ('text_ko', models.CharField(blank=True, max_length=500)),
                ('text_fr', models.CharField(blank=True, max_length=500)),
                ('text_ru', models.CharField(blank=True, max_length=500)),
                ('text_de', models.CharField(blank=True, max_length=500)),
                ('text_es', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
