# Generated by Django 5.1.6 on 2025-03-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a26', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='cid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddIndex(
            model_name='coordinate',
            index=models.Index(fields=['label'], name='misc_a26_co_label_5db15c_idx'),
        ),
    ]
