# Generated by Django 5.1.6 on 2025-03-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a26', '0002_alter_coordinate_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='z',
            field=models.FloatField(),
        ),
    ]
