# Generated by Django 5.1.6 on 2025-04-01 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a26', '0003_alter_coordinate_x_alter_coordinate_z'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(unique=True)),
                ('extra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questextra', to='misc_a26.text')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a26.text')),
            ],
        ),
    ]
