# Generated by Django 4.0.2 on 2022-03-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a23', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='char_en',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='character',
            name='char_ja',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='character',
            name='char_ko',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='character',
            name='char_sc',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='character',
            name='char_tc',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='character',
            name='slug',
            field=models.SlugField(max_length=11),
        ),
    ]
