# Generated by Django 3.0.6 on 2021-06-11 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('effects_a16', '0001_initial'),
        ('items_a16', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EffectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_elem', models.IntegerField()),
                ('max_elem', models.IntegerField()),
                ('number', models.IntegerField()),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effects_a16.Effect')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='EffectLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elem', models.CharField(max_length=10)),
                ('hidden', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('effects', models.ManyToManyField(to='items_a16.EffectData')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a16.Item')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
