# Generated by Django 5.0.5 on 2024-06-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_a16', '0003_auto_20210611_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='slugname',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='slugname',
            new_name='slug',
        ),
    ]
