# Generated by Django 3.0.6 on 2021-06-11 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monsters_a16', '0001_initial'),
        ('items_a16', '0003_auto_20210611_0137'),
        ('regions_a16', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('ingredients', models.ManyToManyField(to='items_a16.Item')),
                ('monsters', models.ManyToManyField(to='monsters_a16.Monster')),
                ('rare', models.ManyToManyField(related_name='rareitems', to='items_a16.Item')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions_a16.Region')),
                ('relics', models.ManyToManyField(related_name='relicitems', to='items_a16.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.ManyToManyField(to='areadata_a16.Field')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions_a16.Region')),
            ],
        ),
    ]
