# Generated by Django 4.0.3 on 2022-03-02 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_a23', '0007_remove_book_chest_remove_item_chest'),
        ('regions_a23', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatherItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a23.item')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='GatherNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=35)),
                ('tool', models.CharField(max_length=10)),
                ('items', models.ManyToManyField(to='regions_a23.gatheritem')),
            ],
        ),
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.CharField(max_length=250)),
                ('weather', models.CharField(max_length=10)),
                ('loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions_a23.region')),
                ('node', models.ManyToManyField(to='regions_a23.gathernode')),
            ],
            options={
                'ordering': ['loc'],
            },
        ),
        migrations.CreateModel(
            name='Chest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a23.book')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a23.item')),
                ('loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions_a23.region')),
            ],
        ),
    ]
