# Generated by Django 4.0.3 on 2022-03-03 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions_a23', '0002_gatheritem_gathernode_climate_chest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gathernode',
            options={'ordering': ['tool']},
        ),
    ]
