# Generated by Django 4.0.3 on 2022-03-04 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_a23', '0007_remove_book_chest_remove_item_chest'),
        ('regions_a23', '0003_alter_gathernode_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Climate2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.CharField(max_length=250)),
                ('weather', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['loc'],
            },
        ),
        migrations.CreateModel(
            name='Region2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30)),
                ('reg_en', models.CharField(max_length=30)),
                ('reg_ja', models.CharField(max_length=30)),
                ('reg_ko', models.CharField(max_length=30)),
                ('reg_sc', models.CharField(max_length=30)),
                ('reg_tc', models.CharField(max_length=30)),
                ('child', models.ManyToManyField(to='regions_a23.region2')),
            ],
        ),
        migrations.CreateModel(
            name='GatherNode2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=35)),
                ('tool', models.CharField(max_length=10)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions_a23.climate2')),
            ],
            options={
                'ordering': ['tool'],
            },
        ),
        migrations.CreateModel(
            name='GatherItem2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a23.item')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions_a23.gathernode2')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.AddField(
            model_name='climate2',
            name='loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions_a23.region2'),
        ),
        migrations.CreateModel(
            name='Chest2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a23.book')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a23.item')),
                ('loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions_a23.region2')),
            ],
        ),
    ]
