# Generated by Django 4.0.3 on 2022-03-08 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions_a23', '0005_region2_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climate',
            name='loc',
        ),
        migrations.RemoveField(
            model_name='climate',
            name='node',
        ),
        migrations.RemoveField(
            model_name='gatheritem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='gathernode',
            name='items',
        ),
        migrations.RemoveField(
            model_name='region',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Chest',
        ),
        migrations.DeleteModel(
            name='Climate',
        ),
        migrations.DeleteModel(
            name='GatherItem',
        ),
        migrations.DeleteModel(
            name='GatherNode',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
