# Generated by Django 4.0.3 on 2022-03-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions_a23', '0008_gathernode2_major'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gathernode2',
            options={'ordering': ['tool', 'climate']},
        ),
        migrations.AlterField(
            model_name='gathernode2',
            name='major',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='gathernode2',
            name='tool',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
