# Generated by Django 5.0.5 on 2024-06-19 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories_a12', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slugname',
            new_name='slug',
        ),
    ]
