# Generated by Django 3.0.6 on 2021-06-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a12', '0003_auto_20210609_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effectline',
            name='max_elem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='effectline',
            name='min_elem',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
