# Generated by Django 4.2.5 on 2023-10-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara_a25', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='character',
            name='gacha-char',
        ),
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.SlugField(default='error', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memoria',
            name='slug',
            field=models.SlugField(default='error', unique=True),
            preserve_default=False,
        ),
    ]
