# Generated by Django 4.2.5 on 2023-10-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara_a25', '0002_remove_character_gacha_char_character_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['char', 'index']},
        ),
        migrations.AddField(
            model_name='skill',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='val2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
