# Generated by Django 4.2.5 on 2023-10-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara_a25', '0004_remove_character_rate_hp_remove_character_rate_matk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='memoria',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
