# Generated by Django 4.2.5 on 2023-10-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chara_a25', '0005_character_timestamp_memoria_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='memoria',
            name='timestamp',
        ),
    ]
