# Generated by Django 4.2.5 on 2023-10-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara_a25', '0009_skill_val0_skill_val3_skill_val4_skill_val5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='val0',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
