# Generated by Django 4.2.6 on 2023-10-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara_a25', '0010_alter_skill_val0'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='memoria',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
