# Generated by Django 5.0.2 on 2024-03-23 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara_a25', '0013_character_gbl_memoria_gbl'),
        ('misc_a25', '0019_alter_desc_text_en_alter_desc_text_sc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='leader_skill_desc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader_desc', to='misc_a25.desc'),
        ),
        migrations.AddField(
            model_name='character',
            name='leader_skill_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader_name', to='misc_a25.name'),
        ),
        migrations.AddField(
            model_name='character',
            name='leader_skill_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_tag', to='misc_a25.filterable'),
        ),
        migrations.AddField(
            model_name='character',
            name='tags',
            field=models.ManyToManyField(related_name='chara_tags', to='misc_a25.filterable'),
        ),
    ]
