# Generated by Django 5.0.2 on 2024-03-24 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chara_a25', '0014_character_leader_skill_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoria',
            name='hp1',
        ),
        migrations.RemoveField(
            model_name='memoria',
            name='matk1',
        ),
        migrations.RemoveField(
            model_name='memoria',
            name='mdef1',
        ),
        migrations.RemoveField(
            model_name='memoria',
            name='patk1',
        ),
        migrations.RemoveField(
            model_name='memoria',
            name='pdef1',
        ),
        migrations.RemoveField(
            model_name='memoria',
            name='spd1',
        ),
    ]
