# Generated by Django 5.0.7 on 2024-09-20 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara_a25', '0018_alter_passive_options'),
        ('misc_a25', '0022_alter_desc_text_ja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('kind', models.IntegerField()),
                ('gbl', models.BooleanField(default=False)),
                ('lv1', models.IntegerField()),
                ('lv2', models.IntegerField()),
                ('lv3', models.IntegerField()),
                ('acquisition1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emblem_acquisition1', to='misc_a25.desc')),
                ('acquisition2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emblem_acquisition2', to='misc_a25.desc')),
                ('acquisition3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emblem_acquisition3', to='misc_a25.desc')),
                ('desc1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emblem_desc1', to='misc_a25.desc')),
                ('desc2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emblem_desc2', to='misc_a25.desc')),
                ('desc3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emblem_desc3', to='misc_a25.desc')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc_a25.name')),
            ],
            options={
                'ordering': ['kind', 'index'],
            },
        ),
    ]
