# Generated by Django 5.0.7 on 2024-09-20 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara_a25', '0019_emblem'),
        ('misc_a25', '0022_alter_desc_text_ja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emblem',
            name='desc1',
        ),
        migrations.RemoveField(
            model_name='emblem',
            name='desc2',
        ),
        migrations.RemoveField(
            model_name='emblem',
            name='desc3',
        ),
        migrations.AddField(
            model_name='emblem',
            name='desc',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='misc_a25.desc'),
            preserve_default=False,
        ),
    ]
