# Generated by Django 5.1.2 on 2024-11-16 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara_a25', '0022_alter_character_options_alter_memoria_options_and_more'),
        ('misc_a25', '0023_alter_name_text_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoria',
            name='illustrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='illust', to='misc_a25.name'),
        ),
    ]
