# Generated by Django 5.1.6 on 2025-03-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara_a25', '0023_memoria_illustrator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['-date', 'role', '-rarity', 'slug']},
        ),
        migrations.AddField(
            model_name='character',
            name='six_star',
            field=models.BooleanField(default=False),
        ),
    ]
