# Generated by Django 5.1.6 on 2025-03-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara_a25', '0024_alter_character_options_character_six_star_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='break6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='pow6',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
