# Generated by Django 5.1.6 on 2025-03-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara_a25', '0025_alter_skill_break6_alter_skill_pow6'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='evol',
            field=models.BooleanField(default=False),
        ),
    ]
