# Generated by Django 5.1.6 on 2025-03-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara_a25', '0026_skill_evol'),
    ]

    operations = [
        migrations.AddField(
            model_name='passive',
            name='evol',
            field=models.BooleanField(default=False),
        ),
    ]
