# Generated by Django 5.1.6 on 2025-03-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara_a25', '0027_passive_evol'),
    ]

    operations = [
        migrations.AddField(
            model_name='passive',
            name='val5',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
