# Generated by Django 5.1.6 on 2025-03-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara_a25', '0028_passive_val5'),
    ]

    operations = [
        migrations.AddField(
            model_name='passive',
            name='val6',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
