# Generated by Django 5.1.6 on 2025-04-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara_a25', '0030_alter_skill_break1_alter_skill_break2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='val7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='val7_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='val8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='val8_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
