# Generated by Django 3.0.6 on 2021-04-13 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories_a22', '0001_initial'),
        ('traits_a22', '0001_initial'),
        ('locations_a22', '0003_location_isdlc'),
        ('effects_a22', '0003_auto_20210412_0555'),
        ('shops_a22', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugname', models.SlugField(unique=True)),
                ('itemtype', models.CharField(blank=True, max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('index', models.IntegerField()),
                ('level', models.IntegerField()),
                ('isDLC', models.BooleanField(default=False)),
                ('ice', models.BooleanField(default=False)),
                ('wind', models.BooleanField(default=False)),
                ('lightning', models.BooleanField(default=False)),
                ('fire', models.BooleanField(default=False)),
                ('elementvalue', models.IntegerField()),
                ('skilltree', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(to='categories_a22.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Item_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Item_fr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Item_ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Item_ko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Item_sc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Item_tc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UsableItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wt', models.IntegerField()),
                ('stun', models.IntegerField()),
                ('cc', models.IntegerField()),
                ('cooltime', models.IntegerField()),
                ('effrange', models.CharField(max_length=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a22.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ShopDevelop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addCat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addCat', to='categories_a22.Category')),
                ('addProd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addProd', to='items_a22.Item')),
                ('cat1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopdevcat1', to='categories_a22.Category')),
                ('cat2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopdevcat2', to='categories_a22.Category')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a22.Item')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeMorphs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a22.Item')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morphparent', to='items_a22.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_en',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_a22.Item_en'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_fr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_a22.Item_fr'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_ja',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_a22.Item_ja'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_ko',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_a22.Item_ko'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_sc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_a22.Item_sc'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_tc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items_a22.Item_tc'),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ManyToManyField(blank=True, to='locations_a22.Location'),
        ),
        migrations.AddField(
            model_name='item',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops_a22.Shop'),
        ),
        migrations.AddField(
            model_name='item',
            name='trait',
            field=models.ManyToManyField(blank=True, to='traits_a22.Trait'),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('ice', models.BooleanField(default=False)),
                ('wind', models.BooleanField(default=False)),
                ('lightning', models.BooleanField(default=False)),
                ('fire', models.BooleanField(default=False)),
                ('unlockelem', models.CharField(blank=True, max_length=10, null=True)),
                ('unlockvalue', models.IntegerField(blank=True, null=True)),
                ('unlockquality', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientcat', to='categories_a22.Category')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientitem', to='items_a22.Item')),
                ('synthitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a22.Item')),
            ],
        ),
        migrations.CreateModel(
            name='IngEffects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('value', models.IntegerField()),
                ('essence', models.BooleanField(default=False)),
                ('effect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='effects_a22.Effect')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a22.Ingredient')),
                ('morph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a22.Item')),
            ],
        ),
        migrations.CreateModel(
            name='EVLinkItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item1', to='items_a22.Item')),
                ('item2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item2', to='items_a22.Item')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a22.Item')),
            ],
        ),
        migrations.CreateModel(
            name='EffectLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('number', models.IntegerField()),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effects_a22.Effect')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_a22.Item')),
            ],
        ),
    ]
