# Generated by Django 3.0.6 on 2021-04-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_a22', '0002_auto_20210413_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingeffects',
            name='noneffect',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
