# Generated by Django 3.0.6 on 2021-05-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_a22', '0010_auto_20210502_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlocations',
            name='area',
        ),
        migrations.RemoveField(
            model_name='itemlocations',
            name='text',
        ),
    ]
