# Generated by Django 3.0.6 on 2021-05-02 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_a22', '0011_auto_20210502_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemregions',
            name='areas',
        ),
        migrations.AddField(
            model_name='itemareas',
            name='areas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_a22.ItemRegions'),
        ),
    ]
