# Generated by Django 3.0.6 on 2021-05-08 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories_a22', '0001_initial'),
        ('items_a22', '0012_auto_20210502_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='effectline',
            options={'ordering': ['line', 'number']},
        ),
        migrations.AlterModelOptions(
            name='ingeffects',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='recipemorphs',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='itemareas',
            name='areas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='items_a22.ItemRegions'),
        ),
        migrations.CreateModel(
            name='CategoryItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='categories_a22.Category')),
                ('ingredients', models.ManyToManyField(related_name='catings', to='items_a22.Item')),
                ('items', models.ManyToManyField(related_name='catitems', to='items_a22.Item')),
            ],
        ),
    ]
