# Generated by Django 3.2.9 on 2021-12-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_a22', '0013_auto_20210508_0729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['index']},
        ),
    ]
