# Generated by Django 5.0.5 on 2024-06-19 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_a22', '0015_rename_slugname_item_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_en',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='item_fr',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='item_ja',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='item_ko',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='item_sc',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='item_tc',
            old_name='description',
            new_name='desc',
        ),
    ]
