# Generated by Django 4.0.3 on 2022-03-04 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc_a23', '0003_alter_character_char_en_alter_character_char_ja_and_more'),
        ('monsters_a23', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='char1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='char1', to='misc_a23.character'),
        ),
        migrations.AddField(
            model_name='monster',
            name='char2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='char2', to='misc_a23.character'),
        ),
        migrations.AddField(
            model_name='monster',
            name='char3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='char3', to='misc_a23.character'),
        ),
        migrations.AddField(
            model_name='monster',
            name='char4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='char4', to='misc_a23.character'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='kind',
            field=models.CharField(max_length=15),
        ),
    ]
