# Generated by Django 4.0.3 on 2022-03-04 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monsters_a23', '0002_monster_char1_monster_char2_monster_char3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='mon_en',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monsters_a23.monster_en'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='mon_ja',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monsters_a23.monster_ja'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='mon_ko',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monsters_a23.monster_ko'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='mon_sc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monsters_a23.monster_sc'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='mon_tc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monsters_a23.monster_tc'),
        ),
    ]
