# Generated by Django 4.0.3 on 2022-03-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters_a23', '0003_alter_monster_mon_en_alter_monster_mon_ja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='resist_fire',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='resist_ice',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='resist_mag',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='resist_phys',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='resist_thun',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='resist_wind',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
