# Generated by Django 4.0.3 on 2022-03-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions_a23', '0005_region2_parent'),
        ('monsters_a23', '0004_alter_monster_resist_fire_alter_monster_resist_ice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='location',
            field=models.ManyToManyField(to='regions_a23.region2'),
        ),
    ]
