# Generated by Django 4.0.3 on 2022-03-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsters_a23', '0005_alter_monster_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='location',
        ),
    ]
